// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.36.2
// source: log.proto

package logv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// LogEntry represents a single log record.
type LogEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	TenantId      string                 `protobuf:"bytes,2,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	DeviceId      string                 `protobuf:"bytes,3,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	AgentId       string                 `protobuf:"bytes,4,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	TaskId        string                 `protobuf:"bytes,5,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Level         string                 `protobuf:"bytes,7,opt,name=level,proto3" json:"level,omitempty"`
	Source        string                 `protobuf:"bytes,8,opt,name=source,proto3" json:"source,omitempty"`
	Message       string                 `protobuf:"bytes,9,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogEntry) Reset() {
	*x = LogEntry{}
	mi := &file_log_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogEntry) ProtoMessage() {}

func (x *LogEntry) ProtoReflect() protoreflect.Message {
	mi := &file_log_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogEntry.ProtoReflect.Descriptor instead.
func (*LogEntry) Descriptor() ([]byte, []int) {
	return file_log_proto_rawDescGZIP(), []int{0}
}

func (x *LogEntry) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *LogEntry) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *LogEntry) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *LogEntry) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *LogEntry) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *LogEntry) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *LogEntry) GetLevel() string {
	if x != nil {
		return x.Level
	}
	return ""
}

func (x *LogEntry) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *LogEntry) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// SearchLogsRequest is the request to search logs.
type SearchLogsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantId      string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	DeviceId      string                 `protobuf:"bytes,2,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	AgentId       string                 `protobuf:"bytes,3,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	Level         string                 `protobuf:"bytes,4,opt,name=level,proto3" json:"level,omitempty"`
	Source        string                 `protobuf:"bytes,5,opt,name=source,proto3" json:"source,omitempty"`
	Keyword       string                 `protobuf:"bytes,6,opt,name=keyword,proto3" json:"keyword,omitempty"`
	Q             string                 `protobuf:"bytes,7,opt,name=q,proto3" json:"q,omitempty"`
	From          *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=from,proto3" json:"from,omitempty"`
	To            *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=to,proto3" json:"to,omitempty"`
	Limit         int32                  `protobuf:"varint,10,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        int32                  `protobuf:"varint,11,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchLogsRequest) Reset() {
	*x = SearchLogsRequest{}
	mi := &file_log_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchLogsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchLogsRequest) ProtoMessage() {}

func (x *SearchLogsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_log_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchLogsRequest.ProtoReflect.Descriptor instead.
func (*SearchLogsRequest) Descriptor() ([]byte, []int) {
	return file_log_proto_rawDescGZIP(), []int{1}
}

func (x *SearchLogsRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *SearchLogsRequest) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *SearchLogsRequest) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *SearchLogsRequest) GetLevel() string {
	if x != nil {
		return x.Level
	}
	return ""
}

func (x *SearchLogsRequest) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *SearchLogsRequest) GetKeyword() string {
	if x != nil {
		return x.Keyword
	}
	return ""
}

func (x *SearchLogsRequest) GetQ() string {
	if x != nil {
		return x.Q
	}
	return ""
}

func (x *SearchLogsRequest) GetFrom() *timestamppb.Timestamp {
	if x != nil {
		return x.From
	}
	return nil
}

func (x *SearchLogsRequest) GetTo() *timestamppb.Timestamp {
	if x != nil {
		return x.To
	}
	return nil
}

func (x *SearchLogsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *SearchLogsRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

// SearchLogsResponse contains search results.
type SearchLogsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Entries       []*LogEntry            `protobuf:"bytes,1,rep,name=entries,proto3" json:"entries,omitempty"`
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchLogsResponse) Reset() {
	*x = SearchLogsResponse{}
	mi := &file_log_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchLogsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchLogsResponse) ProtoMessage() {}

func (x *SearchLogsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_log_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchLogsResponse.ProtoReflect.Descriptor instead.
func (*SearchLogsResponse) Descriptor() ([]byte, []int) {
	return file_log_proto_rawDescGZIP(), []int{2}
}

func (x *SearchLogsResponse) GetEntries() []*LogEntry {
	if x != nil {
		return x.Entries
	}
	return nil
}

func (x *SearchLogsResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

// AppendLogRequest is the request to append a log entry.
type AppendLogRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantId      string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	DeviceId      string                 `protobuf:"bytes,2,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	AgentId       string                 `protobuf:"bytes,3,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	TaskId        string                 `protobuf:"bytes,4,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	Level         string                 `protobuf:"bytes,5,opt,name=level,proto3" json:"level,omitempty"`
	Source        string                 `protobuf:"bytes,6,opt,name=source,proto3" json:"source,omitempty"`
	Message       string                 `protobuf:"bytes,7,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AppendLogRequest) Reset() {
	*x = AppendLogRequest{}
	mi := &file_log_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AppendLogRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AppendLogRequest) ProtoMessage() {}

func (x *AppendLogRequest) ProtoReflect() protoreflect.Message {
	mi := &file_log_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AppendLogRequest.ProtoReflect.Descriptor instead.
func (*AppendLogRequest) Descriptor() ([]byte, []int) {
	return file_log_proto_rawDescGZIP(), []int{3}
}

func (x *AppendLogRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *AppendLogRequest) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *AppendLogRequest) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *AppendLogRequest) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *AppendLogRequest) GetLevel() string {
	if x != nil {
		return x.Level
	}
	return ""
}

func (x *AppendLogRequest) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *AppendLogRequest) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// GetLogStatsRequest is the request for log statistics.
type GetLogStatsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantId      string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	From          *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=from,proto3" json:"from,omitempty"`
	To            *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=to,proto3" json:"to,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLogStatsRequest) Reset() {
	*x = GetLogStatsRequest{}
	mi := &file_log_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLogStatsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLogStatsRequest) ProtoMessage() {}

func (x *GetLogStatsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_log_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLogStatsRequest.ProtoReflect.Descriptor instead.
func (*GetLogStatsRequest) Descriptor() ([]byte, []int) {
	return file_log_proto_rawDescGZIP(), []int{4}
}

func (x *GetLogStatsRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *GetLogStatsRequest) GetFrom() *timestamppb.Timestamp {
	if x != nil {
		return x.From
	}
	return nil
}

func (x *GetLogStatsRequest) GetTo() *timestamppb.Timestamp {
	if x != nil {
		return x.To
	}
	return nil
}

// GetLogStatsResponse contains log statistics.
type GetLogStatsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TotalEntries  int64                  `protobuf:"varint,1,opt,name=total_entries,json=totalEntries,proto3" json:"total_entries,omitempty"`
	ErrorCount    int64                  `protobuf:"varint,2,opt,name=error_count,json=errorCount,proto3" json:"error_count,omitempty"`
	WarnCount     int64                  `protobuf:"varint,3,opt,name=warn_count,json=warnCount,proto3" json:"warn_count,omitempty"`
	InfoCount     int64                  `protobuf:"varint,4,opt,name=info_count,json=infoCount,proto3" json:"info_count,omitempty"`
	SourceCounts  map[string]int64       `protobuf:"bytes,5,rep,name=source_counts,json=sourceCounts,proto3" json:"source_counts,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLogStatsResponse) Reset() {
	*x = GetLogStatsResponse{}
	mi := &file_log_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLogStatsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLogStatsResponse) ProtoMessage() {}

func (x *GetLogStatsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_log_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLogStatsResponse.ProtoReflect.Descriptor instead.
func (*GetLogStatsResponse) Descriptor() ([]byte, []int) {
	return file_log_proto_rawDescGZIP(), []int{5}
}

func (x *GetLogStatsResponse) GetTotalEntries() int64 {
	if x != nil {
		return x.TotalEntries
	}
	return 0
}

func (x *GetLogStatsResponse) GetErrorCount() int64 {
	if x != nil {
		return x.ErrorCount
	}
	return 0
}

func (x *GetLogStatsResponse) GetWarnCount() int64 {
	if x != nil {
		return x.WarnCount
	}
	return 0
}

func (x *GetLogStatsResponse) GetInfoCount() int64 {
	if x != nil {
		return x.InfoCount
	}
	return 0
}

func (x *GetLogStatsResponse) GetSourceCounts() map[string]int64 {
	if x != nil {
		return x.SourceCounts
	}
	return nil
}

// ListLogSourcesRequest is the request to list log sources.
type ListLogSourcesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantId      string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListLogSourcesRequest) Reset() {
	*x = ListLogSourcesRequest{}
	mi := &file_log_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListLogSourcesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListLogSourcesRequest) ProtoMessage() {}

func (x *ListLogSourcesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_log_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListLogSourcesRequest.ProtoReflect.Descriptor instead.
func (*ListLogSourcesRequest) Descriptor() ([]byte, []int) {
	return file_log_proto_rawDescGZIP(), []int{6}
}

func (x *ListLogSourcesRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

// ListLogSourcesResponse contains distinct log sources.
type ListLogSourcesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sources       []string               `protobuf:"bytes,1,rep,name=sources,proto3" json:"sources,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListLogSourcesResponse) Reset() {
	*x = ListLogSourcesResponse{}
	mi := &file_log_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListLogSourcesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListLogSourcesResponse) ProtoMessage() {}

func (x *ListLogSourcesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_log_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListLogSourcesResponse.ProtoReflect.Descriptor instead.
func (*ListLogSourcesResponse) Descriptor() ([]byte, []int) {
	return file_log_proto_rawDescGZIP(), []int{7}
}

func (x *ListLogSourcesResponse) GetSources() []string {
	if x != nil {
		return x.Sources
	}
	return nil
}

var File_log_proto protoreflect.FileDescriptor

const file_log_proto_rawDesc = "" +
	"\n" +
	"\tlog.proto\x12\x0eopsmesh.log.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\x8a\x02\n" +
	"\bLogEntry\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1b\n" +
	"\ttenant_id\x18\x02 \x01(\tR\btenantId\x12\x1b\n" +
	"\tdevice_id\x18\x03 \x01(\tR\bdeviceId\x12\x19\n" +
	"\bagent_id\x18\x04 \x01(\tR\aagentId\x12\x17\n" +
	"\atask_id\x18\x05 \x01(\tR\x06taskId\x128\n" +
	"\ttimestamp\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12\x14\n" +
	"\x05level\x18\a \x01(\tR\x05level\x12\x16\n" +
	"\x06source\x18\b \x01(\tR\x06source\x12\x18\n" +
	"\amessage\x18\t \x01(\tR\amessage\"\xc8\x02\n" +
	"\x11SearchLogsRequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12\x1b\n" +
	"\tdevice_id\x18\x02 \x01(\tR\bdeviceId\x12\x19\n" +
	"\bagent_id\x18\x03 \x01(\tR\aagentId\x12\x14\n" +
	"\x05level\x18\x04 \x01(\tR\x05level\x12\x16\n" +
	"\x06source\x18\x05 \x01(\tR\x06source\x12\x18\n" +
	"\akeyword\x18\x06 \x01(\tR\akeyword\x12\f\n" +
	"\x01q\x18\a \x01(\tR\x01q\x12.\n" +
	"\x04from\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\x04from\x12*\n" +
	"\x02to\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\x02to\x12\x14\n" +
	"\x05limit\x18\n" +
	" \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\v \x01(\x05R\x06offset\"^\n" +
	"\x12SearchLogsResponse\x122\n" +
	"\aentries\x18\x01 \x03(\v2\x18.opsmesh.log.v1.LogEntryR\aentries\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total\"\xc8\x01\n" +
	"\x10AppendLogRequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12\x1b\n" +
	"\tdevice_id\x18\x02 \x01(\tR\bdeviceId\x12\x19\n" +
	"\bagent_id\x18\x03 \x01(\tR\aagentId\x12\x17\n" +
	"\atask_id\x18\x04 \x01(\tR\x06taskId\x12\x14\n" +
	"\x05level\x18\x05 \x01(\tR\x05level\x12\x16\n" +
	"\x06source\x18\x06 \x01(\tR\x06source\x12\x18\n" +
	"\amessage\x18\a \x01(\tR\amessage\"\x8d\x01\n" +
	"\x12GetLogStatsRequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12.\n" +
	"\x04from\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\x04from\x12*\n" +
	"\x02to\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\x02to\"\xb6\x02\n" +
	"\x13GetLogStatsResponse\x12#\n" +
	"\rtotal_entries\x18\x01 \x01(\x03R\ftotalEntries\x12\x1f\n" +
	"\verror_count\x18\x02 \x01(\x03R\n" +
	"errorCount\x12\x1d\n" +
	"\n" +
	"warn_count\x18\x03 \x01(\x03R\twarnCount\x12\x1d\n" +
	"\n" +
	"info_count\x18\x04 \x01(\x03R\tinfoCount\x12Z\n" +
	"\rsource_counts\x18\x05 \x03(\v25.opsmesh.log.v1.GetLogStatsResponse.SourceCountsEntryR\fsourceCounts\x1a?\n" +
	"\x11SourceCountsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x03R\x05value:\x028\x01\"4\n" +
	"\x15ListLogSourcesRequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\"2\n" +
	"\x16ListLogSourcesResponse\x12\x18\n" +
	"\asources\x18\x01 \x03(\tR\asources2\xe3\x02\n" +
	"\n" +
	"LogService\x12S\n" +
	"\n" +
	"SearchLogs\x12!.opsmesh.log.v1.SearchLogsRequest\x1a\".opsmesh.log.v1.SearchLogsResponse\x12G\n" +
	"\tAppendLog\x12 .opsmesh.log.v1.AppendLogRequest\x1a\x18.opsmesh.log.v1.LogEntry\x12V\n" +
	"\vGetLogStats\x12\".opsmesh.log.v1.GetLogStatsRequest\x1a#.opsmesh.log.v1.GetLogStatsResponse\x12_\n" +
	"\x0eListLogSources\x12%.opsmesh.log.v1.ListLogSourcesRequest\x1a&.opsmesh.log.v1.ListLogSourcesResponseB'Z%opsmesh.io/log-svc/api/proto/v1;logv1b\x06proto3"

var (
	file_log_proto_rawDescOnce sync.Once
	file_log_proto_rawDescData []byte
)

func file_log_proto_rawDescGZIP() []byte {
	file_log_proto_rawDescOnce.Do(func() {
		file_log_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_log_proto_rawDesc), len(file_log_proto_rawDesc)))
	})
	return file_log_proto_rawDescData
}

var file_log_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_log_proto_goTypes = []any{
	(*LogEntry)(nil),               // 0: opsmesh.log.v1.LogEntry
	(*SearchLogsRequest)(nil),      // 1: opsmesh.log.v1.SearchLogsRequest
	(*SearchLogsResponse)(nil),     // 2: opsmesh.log.v1.SearchLogsResponse
	(*AppendLogRequest)(nil),       // 3: opsmesh.log.v1.AppendLogRequest
	(*GetLogStatsRequest)(nil),     // 4: opsmesh.log.v1.GetLogStatsRequest
	(*GetLogStatsResponse)(nil),    // 5: opsmesh.log.v1.GetLogStatsResponse
	(*ListLogSourcesRequest)(nil),  // 6: opsmesh.log.v1.ListLogSourcesRequest
	(*ListLogSourcesResponse)(nil), // 7: opsmesh.log.v1.ListLogSourcesResponse
	nil,                            // 8: opsmesh.log.v1.GetLogStatsResponse.SourceCountsEntry
	(*timestamppb.Timestamp)(nil),  // 9: google.protobuf.Timestamp
}
var file_log_proto_depIdxs = []int32{
	9,  // 0: opsmesh.log.v1.LogEntry.timestamp:type_name -> google.protobuf.Timestamp
	9,  // 1: opsmesh.log.v1.SearchLogsRequest.from:type_name -> google.protobuf.Timestamp
	9,  // 2: opsmesh.log.v1.SearchLogsRequest.to:type_name -> google.protobuf.Timestamp
	0,  // 3: opsmesh.log.v1.SearchLogsResponse.entries:type_name -> opsmesh.log.v1.LogEntry
	9,  // 4: opsmesh.log.v1.GetLogStatsRequest.from:type_name -> google.protobuf.Timestamp
	9,  // 5: opsmesh.log.v1.GetLogStatsRequest.to:type_name -> google.protobuf.Timestamp
	8,  // 6: opsmesh.log.v1.GetLogStatsResponse.source_counts:type_name -> opsmesh.log.v1.GetLogStatsResponse.SourceCountsEntry
	1,  // 7: opsmesh.log.v1.LogService.SearchLogs:input_type -> opsmesh.log.v1.SearchLogsRequest
	3,  // 8: opsmesh.log.v1.LogService.AppendLog:input_type -> opsmesh.log.v1.AppendLogRequest
	4,  // 9: opsmesh.log.v1.LogService.GetLogStats:input_type -> opsmesh.log.v1.GetLogStatsRequest
	6,  // 10: opsmesh.log.v1.LogService.ListLogSources:input_type -> opsmesh.log.v1.ListLogSourcesRequest
	2,  // 11: opsmesh.log.v1.LogService.SearchLogs:output_type -> opsmesh.log.v1.SearchLogsResponse
	0,  // 12: opsmesh.log.v1.LogService.AppendLog:output_type -> opsmesh.log.v1.LogEntry
	5,  // 13: opsmesh.log.v1.LogService.GetLogStats:output_type -> opsmesh.log.v1.GetLogStatsResponse
	7,  // 14: opsmesh.log.v1.LogService.ListLogSources:output_type -> opsmesh.log.v1.ListLogSourcesResponse
	11, // [11:15] is the sub-list for method output_type
	7,  // [7:11] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_log_proto_init() }
func file_log_proto_init() {
	if File_log_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_log_proto_rawDesc), len(file_log_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_log_proto_goTypes,
		DependencyIndexes: file_log_proto_depIdxs,
		MessageInfos:      file_log_proto_msgTypes,
	}.Build()
	File_log_proto = out.File
	file_log_proto_goTypes = nil
	file_log_proto_depIdxs = nil
}
