//go:build !ignore_autogenerated

// Code generated by opsmesh-operator. DO NOT EDIT.
// Hand-written DeepCopy methods to avoid pulling in controller-gen tooling.
// Each method mirrors what controller-gen would emit for the v1alpha1 API.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto copies all properties of MySQLSpec into dst.
func (in *MySQLSpec) DeepCopyInto(dst *MySQLSpec) {
	*dst = *in
}

// DeepCopy returns a deep copy of MySQLSpec.
func (in *MySQLSpec) DeepCopy() *MySQLSpec {
	if in == nil {
		return nil
	}
	out := new(MySQLSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto copies all properties of RedisSpec into dst.
func (in *RedisSpec) DeepCopyInto(dst *RedisSpec) {
	*dst = *in
}

// DeepCopy returns a deep copy of RedisSpec.
func (in *RedisSpec) DeepCopy() *RedisSpec {
	if in == nil {
		return nil
	}
	out := new(RedisSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto copies all properties of OpsMeshInstanceSpec into dst.
func (in *OpsMeshInstanceSpec) DeepCopyInto(dst *OpsMeshInstanceSpec) {
	*dst = *in
	in.MySQL.DeepCopyInto(&dst.MySQL)
	in.Redis.DeepCopyInto(&dst.Redis)
}

// DeepCopy returns a deep copy of OpsMeshInstanceSpec.
func (in *OpsMeshInstanceSpec) DeepCopy() *OpsMeshInstanceSpec {
	if in == nil {
		return nil
	}
	out := new(OpsMeshInstanceSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto copies all properties of OpsMeshInstanceStatus into dst.
func (in *OpsMeshInstanceStatus) DeepCopyInto(dst *OpsMeshInstanceStatus) {
	*dst = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &dst.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy returns a deep copy of OpsMeshInstanceStatus.
func (in *OpsMeshInstanceStatus) DeepCopy() *OpsMeshInstanceStatus {
	if in == nil {
		return nil
	}
	out := new(OpsMeshInstanceStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto copies all properties of OpsMeshInstance into dst.
func (in *OpsMeshInstance) DeepCopyInto(dst *OpsMeshInstance) {
	*dst = *in
	out := dst
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy returns a deep copy of OpsMeshInstance.
func (in *OpsMeshInstance) DeepCopy() *OpsMeshInstance {
	if in == nil {
		return nil
	}
	out := new(OpsMeshInstance)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject returns a runtime.Object deep copy of OpsMeshInstance.
func (in *OpsMeshInstance) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto copies all properties of OpsMeshInstanceList into dst.
func (in *OpsMeshInstanceList) DeepCopyInto(dst *OpsMeshInstanceList) {
	*dst = *in
	out := dst
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &dst.Items
		*out = make([]OpsMeshInstance, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy returns a deep copy of OpsMeshInstanceList.
func (in *OpsMeshInstanceList) DeepCopy() *OpsMeshInstanceList {
	if in == nil {
		return nil
	}
	out := new(OpsMeshInstanceList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject returns a runtime.Object deep copy of OpsMeshInstanceList.
func (in *OpsMeshInstanceList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}
