// Code generated by protoc-gen-go. DO NOT EDIT.
// source: opsmesh/v1/registration.proto
//
// M3-3A protobuf 生成 stub（消息结构体）。
// 本文件由 proto/scripts/gen.sh (buf generate) 产出，提交到仓库以支持无 Docker 环境编译。
// 重新生成会覆盖本文件；手工修改会在下次生成时丢失。
//
// 兼容期：本包消息与 internal/proto（JSON 友好结构体）并存，由 internal/grpcx/stub.go 互转。
// 服务端/客户端默认仍走 internal/grpcx 手写 ServiceDesc + JSONCodec；生成 stub 经
// grpcx.StubAdapter 桥接后可灰度切换到 protobuf codec。

package pbv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	unsafe "unsafe" // 用于 MessageStateOf 的 unsafe.Pointer 转换（M4-4C 兼容性修复）

	_ "google.golang.org/protobuf/types/known/timestamppb" // 注册 google.protobuf.Timestamp
)

// 兼容性修复（M4-4C 临时）：protobuf v1.33.0 的 MessageStateOf 期望 unsafe.Pointer，
// 生成代码直接传 typed pointer；各调用点已改为 unsafe.Pointer(x) 恢复兼容。
// 重新生成代码时若 protoc-gen-go 版本匹配可移除转换。



// ===== 消息结构体 =====
// 每个消息嵌入 protoimpl.MessageState（v2 API 标准模式），实现 proto.Message 接口。
// 字段标签同时带 protobuf（真实序列化）和 json（JSON codec 兼容期复用）。

// AgentInfo agent 注册/心跳时上报的元信息。
type AgentInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentId       string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	Hostname      string                 `protobuf:"bytes,2,opt,name=hostname,proto3" json:"hostname,omitempty"`
	Segment       string                 `protobuf:"bytes,3,opt,name=segment,proto3" json:"segment,omitempty"`
	TenantId      string                 `protobuf:"bytes,4,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	Addr          string                 `protobuf:"bytes,5,opt,name=addr,proto3" json:"addr,omitempty"`
	GrpcPort      int32                  `protobuf:"varint,6,opt,name=grpc_port,json=grpcPort,proto3" json:"grpc_port,omitempty"`
	MetricsPort   int32                  `protobuf:"varint,7,opt,name=metrics_port,json=metricsPort,proto3" json:"metrics_port,omitempty"`
	Status        string                 `protobuf:"bytes,8,opt,name=status,proto3" json:"status,omitempty"`
	Load          int32                  `protobuf:"varint,9,opt,name=load,proto3" json:"load,omitempty"`
	LastSeen      *Timestamp             `protobuf:"bytes,10,opt,name=last_seen,json=lastSeen,proto3" json:"last_seen,omitempty"`
	InstallToken  string                 `protobuf:"bytes,11,opt,name=install_token,json=installToken,proto3" json:"install_token,omitempty"`
	OnboardDeviceId string               `protobuf:"bytes,12,opt,name=onboard_device_id,json=onboardDeviceId,proto3" json:"onboard_device_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentInfo) Reset()         { *x = AgentInfo{} }
func (x *AgentInfo) String() string { return protoimpl.X.MessageStringOf(x) }
func (*AgentInfo) ProtoMessage()    {}
func (x *AgentInfo) ProtoReflect() protoreflect.Message {
	mi := &file_opsmesh_v1_registration_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(unsafe.Pointer(x)))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// CmdbAttr 一条扁平化的 CMDB 属性。
type CmdbAttr struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value         string                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	Type          string                 `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CmdbAttr) Reset()         { *x = CmdbAttr{} }
func (x *CmdbAttr) String() string { return protoimpl.X.MessageStringOf(x) }
func (*CmdbAttr) ProtoMessage()    {}
func (x *CmdbAttr) ProtoReflect() protoreflect.Message {
	mi := &file_opsmesh_v1_registration_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(unsafe.Pointer(x)))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// CmdbReport agent 通过 Heartbeat 上报到控制面的 CMDB 增量数据。
type CmdbReport struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CiType        string                 `protobuf:"bytes,1,opt,name=ci_type,json=ciType,proto3" json:"ci_type,omitempty"`
	Seq           int64                  `protobuf:"varint,2,opt,name=seq,proto3" json:"seq,omitempty"`
	Attrs         []*CmdbAttr            `protobuf:"bytes,3,rep,name=attrs,proto3" json:"attrs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CmdbReport) Reset()         { *x = CmdbReport{} }
func (x *CmdbReport) String() string { return protoimpl.X.MessageStringOf(x) }
func (*CmdbReport) ProtoMessage()    {}
func (x *CmdbReport) ProtoReflect() protoreflect.Message {
	mi := &file_opsmesh_v1_registration_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(unsafe.Pointer(x)))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Task 控制面下发给 agent 的自动化任务。
type Task struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	AgentId       string                 `protobuf:"bytes,2,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	TenantId      string                 `protobuf:"bytes,3,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	Type          string                 `protobuf:"bytes,4,opt,name=type,proto3" json:"type,omitempty"`
	Command       string                 `protobuf:"bytes,5,opt,name=command,proto3" json:"command,omitempty"`
	Content       string                 `protobuf:"bytes,6,opt,name=content,proto3" json:"content,omitempty"`
	Path          string                 `protobuf:"bytes,7,opt,name=path,proto3" json:"path,omitempty"`
	Status        string                 `protobuf:"bytes,8,opt,name=status,proto3" json:"status,omitempty"`
	ClaimedBy     string                 `protobuf:"bytes,9,opt,name=claimed_by,json=claimedBy,proto3" json:"claimed_by,omitempty"`
	ClaimedAt     *Timestamp             `protobuf:"bytes,10,opt,name=claimed_at,json=claimedAt,proto3" json:"claimed_at,omitempty"`
	CreatedAt     *Timestamp             `protobuf:"bytes,11,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	RetryCount    int32                  `protobuf:"varint,12,opt,name=retry_count,json=retryCount,proto3" json:"retry_count,omitempty"`
	MaxRetries    int32                  `protobuf:"varint,13,opt,name=max_retries,json=maxRetries,proto3" json:"max_retries,omitempty"`
	DeadLetter    bool                   `protobuf:"varint,14,opt,name=dead_letter,json=deadLetter,proto3" json:"dead_letter,omitempty"`
	Schedule      string                 `protobuf:"bytes,15,opt,name=schedule,proto3" json:"schedule,omitempty"`
	ParentId      string                 `protobuf:"bytes,16,opt,name=parent_id,json=parentId,proto3" json:"parent_id,omitempty"`
	LastFiredAt   *Timestamp             `protobuf:"bytes,17,opt,name=last_fired_at,json=lastFiredAt,proto3" json:"last_fired_at,omitempty"`
	DependsOn     []string               `protobuf:"bytes,18,rep,name=depends_on,json=dependsOn,proto3" json:"depends_on,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Task) Reset()         { *x = Task{} }
func (x *Task) String() string { return protoimpl.X.MessageStringOf(x) }
func (*Task) ProtoMessage()    {}
func (x *Task) ProtoReflect() protoreflect.Message {
	mi := &file_opsmesh_v1_registration_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(unsafe.Pointer(x)))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// TaskResult agent 上报的任务执行结果。
type TaskResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	AgentId       string                 `protobuf:"bytes,2,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	ExitCode      int32                  `protobuf:"varint,3,opt,name=exit_code,json=exitCode,proto3" json:"exit_code,omitempty"`
	Stdout        string                 `protobuf:"bytes,4,opt,name=stdout,proto3" json:"stdout,omitempty"`
	Stderr        string                 `protobuf:"bytes,5,opt,name=stderr,proto3" json:"stderr,omitempty"`
	DurationMs    int64                  `protobuf:"varint,6,opt,name=duration_ms,json=durationMs,proto3" json:"duration_ms,omitempty"`
	FinishedAt    *Timestamp             `protobuf:"bytes,7,opt,name=finished_at,json=finishedAt,proto3" json:"finished_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskResult) Reset()         { *x = TaskResult{} }
func (x *TaskResult) String() string { return protoimpl.X.MessageStringOf(x) }
func (*TaskResult) ProtoMessage()    {}
func (x *TaskResult) ProtoReflect() protoreflect.Message {
	mi := &file_opsmesh_v1_registration_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(unsafe.Pointer(x)))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// RegisterResp 控制面注册返回的响应。
type RegisterResp struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	AgentId       string                  `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	ControlConfig map[string]int32        `protobuf:"bytes,2,rep,name=control_config,json=controlConfig,proto3" json:"control_config,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"varint,2,opt,name=value,proto3"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterResp) Reset()         { *x = RegisterResp{} }
func (x *RegisterResp) String() string { return protoimpl.X.MessageStringOf(x) }
func (*RegisterResp) ProtoMessage()    {}
func (x *RegisterResp) ProtoReflect() protoreflect.Message {
	mi := &file_opsmesh_v1_registration_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(unsafe.Pointer(x)))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// HeartbeatReq agent 心跳请求。
type HeartbeatReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentId       string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	Load          int32                  `protobuf:"varint,3,opt,name=load,proto3" json:"load,omitempty"`
	CmdbReport    *CmdbReport            `protobuf:"bytes,4,opt,name=cmdb_report,json=cmdbReport,proto3" json:"cmdb_report,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatReq) Reset()         { *x = HeartbeatReq{} }
func (x *HeartbeatReq) String() string { return protoimpl.X.MessageStringOf(x) }
func (*HeartbeatReq) ProtoMessage()    {}
func (x *HeartbeatReq) ProtoReflect() protoreflect.Message {
	mi := &file_opsmesh_v1_registration_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(unsafe.Pointer(x)))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Empty 无业务负载的空响应。
type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset()         { *x = Empty{} }
func (x *Empty) String() string { return protoimpl.X.MessageStringOf(x) }
func (*Empty) ProtoMessage()    {}
func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_opsmesh_v1_registration_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(unsafe.Pointer(x)))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// PullTasksReq 拉取任务的请求。
type PullTasksReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentId       string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PullTasksReq) Reset()         { *x = PullTasksReq{} }
func (x *PullTasksReq) String() string { return protoimpl.X.MessageStringOf(x) }
func (*PullTasksReq) ProtoMessage()    {}
func (x *PullTasksReq) ProtoReflect() protoreflect.Message {
	mi := &file_opsmesh_v1_registration_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(unsafe.Pointer(x)))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// PullTasksResp 拉取任务的响应。
type PullTasksResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tasks         []*Task                `protobuf:"bytes,1,rep,name=tasks,proto3" json:"tasks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PullTasksResp) Reset()         { *x = PullTasksResp{} }
func (x *PullTasksResp) String() string { return protoimpl.X.MessageStringOf(x) }
func (*PullTasksResp) ProtoMessage()    {}
func (x *PullTasksResp) ProtoReflect() protoreflect.Message {
	mi := &file_opsmesh_v1_registration_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(unsafe.Pointer(x)))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// CancelTaskReq 取消任务的请求。
type CancelTaskReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	TenantId      string                 `protobuf:"bytes,2,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelTaskReq) Reset()         { *x = CancelTaskReq{} }
func (x *CancelTaskReq) String() string { return protoimpl.X.MessageStringOf(x) }
func (*CancelTaskReq) ProtoMessage()    {}
func (x *CancelTaskReq) ProtoReflect() protoreflect.Message {
	mi := &file_opsmesh_v1_registration_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(unsafe.Pointer(x)))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// PollCancelsReq agent 轮询取消信号。
type PollCancelsReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentId       string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PollCancelsReq) Reset()         { *x = PollCancelsReq{} }
func (x *PollCancelsReq) String() string { return protoimpl.X.MessageStringOf(x) }
func (*PollCancelsReq) ProtoMessage()    {}
func (x *PollCancelsReq) ProtoReflect() protoreflect.Message {
	mi := &file_opsmesh_v1_registration_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(unsafe.Pointer(x)))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// PollCancelsResp 控制面返回的已取消任务 ID 列表。
type PollCancelsResp struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	CancelledTaskIds  []string               `protobuf:"bytes,1,rep,name=cancelled_task_ids,json=cancelledTaskIds,proto3" json:"cancelled_task_ids,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *PollCancelsResp) Reset()         { *x = PollCancelsResp{} }
func (x *PollCancelsResp) String() string { return protoimpl.X.MessageStringOf(x) }
func (*PollCancelsResp) ProtoMessage()    {}
func (x *PollCancelsResp) ProtoReflect() protoreflect.Message {
	mi := &file_opsmesh_v1_registration_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(unsafe.Pointer(x)))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}