// Code generated by protoc-gen-go. DO NOT EDIT.
// source: opsmesh/v1/registration.proto
//
// M3-3A protobuf 生成 stub：file descriptor + msgTypes 注册表。
// 本文件提供 ProtoReflect() 所需的 msgTypes 数组。
// 真实 protoc-gen-go 会生成完整的 FileDescriptor 布隆码；此处用最小 MessageInfo
// 占位（GoType 齐全，足以支撑 JSON codec 兼容期与 grpc ServiceDesc 注册）。
// 真实 buf generate 会覆盖为完整布隆码（含 Desc 字段）。

package pbv1

import (
	reflect "reflect"

	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
)

// Timestamp 类型别名，简化消息结构体中时间戳字段书写。
// 真实 protoc-gen-go 会直接用 *timestamppb.Timestamp；别名等价，便于阅读。
type Timestamp = timestamppb.Timestamp

const (
	// Registration_ServiceName 服务全名，与 internal/grpcx 手写 ServiceDesc 同名。
	// 兼容期两条路径注册同一服务名，客户端无需感知服务端走哪条路径。
	Registration_ServiceName = "opsmesh.v1.Registration"
)

// file_opsmesh_v1_registration_proto_msgTypes 是所有消息的 MessageInfo 数组。
// 索引与消息定义顺序一致（AgentInfo=0, CmdbAttr=1, ...）。
// 兼容期主路径走 JSON codec，不依赖 protobuf 反射序列化；真实 buf generate 会填充完整 descriptor。
var file_opsmesh_v1_registration_proto_msgTypes = make([]protoimpl.MessageInfo, 13)

func init() {
	// 为每个消息填充 GoType，使 protoimpl.X.MessageStateOf 能正确返回 MessageInfo。
	// 这保证 ProtoReflect() 不 panic，且 JSON codec（encoding/json）能正常编解码。
	file_opsmesh_v1_registration_proto_msgTypes[0] = newMessageInfo((*AgentInfo)(nil))
	file_opsmesh_v1_registration_proto_msgTypes[1] = newMessageInfo((*CmdbAttr)(nil))
	file_opsmesh_v1_registration_proto_msgTypes[2] = newMessageInfo((*CmdbReport)(nil))
	file_opsmesh_v1_registration_proto_msgTypes[3] = newMessageInfo((*Task)(nil))
	file_opsmesh_v1_registration_proto_msgTypes[4] = newMessageInfo((*TaskResult)(nil))
	file_opsmesh_v1_registration_proto_msgTypes[5] = newMessageInfo((*RegisterResp)(nil))
	file_opsmesh_v1_registration_proto_msgTypes[6] = newMessageInfo((*HeartbeatReq)(nil))
	file_opsmesh_v1_registration_proto_msgTypes[7] = newMessageInfo((*Empty)(nil))
	file_opsmesh_v1_registration_proto_msgTypes[8] = newMessageInfo((*PullTasksReq)(nil))
	file_opsmesh_v1_registration_proto_msgTypes[9] = newMessageInfo((*PullTasksResp)(nil))
	file_opsmesh_v1_registration_proto_msgTypes[10] = newMessageInfo((*CancelTaskReq)(nil))
	file_opsmesh_v1_registration_proto_msgTypes[11] = newMessageInfo((*PollCancelsReq)(nil))
	file_opsmesh_v1_registration_proto_msgTypes[12] = newMessageInfo((*PollCancelsResp)(nil))
}

// newMessageInfo 构造一个只含 GoReflectType 的 MessageInfo。
// 真实 protoc-gen-go 会同时填充 Desc（protoreflect.MessageDescriptor）；此处省略 Desc
// 因为兼容期不走 protobuf 二进制序列化（走 JSON codec），ProtoReflect 仅需不 panic 即可。
// 真实 buf generate 会覆盖本文件为完整实现。
// 兼容性修复（M4-4C 临时）：protobuf v1.33.0 的字段名为 GoReflectType（非 GoType）。
func newMessageInfo(goType any) protoimpl.MessageInfo {
	return protoimpl.MessageInfo{
		GoReflectType: reflect.TypeOf(goType),
	}
}
