// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// source: opsmesh/v1/registration.proto
//
// M3-3A protobuf 生成 stub：gRPC 服务接口 + ServiceDesc + 客户端 stub。
// 本文件由 proto/scripts/gen.sh (buf generate) 产出，提交到仓库以支持无 Docker 环境编译。
//
// JSON codec 为正式契约；此 stub 保留供 buf breaking 守护和未来迁移使用。
// 现有 controlplane/grpc.go 实现 grpcx.RegistrationServer（手写路径，默认）；
// 切换到生成 stub 时用 grpcx.NewStubAdapter 把 grpcx.RegistrationServer 桥接到本接口。

package pbv1

import (
	context "context"

	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// ===== 服务端接口 =====

// RegistrationServer 是生成 stub 的服务端接口（protoc-gen-go-grpc 输出）。
// 与 internal/grpcx.RegistrationServer 方法集一致，但消息类型用本包 pbv1 类型。
// JSON codec 为正式契约；StubAdapter 桥接保留供未来迁移使用：StubAdapter 实现 pbv1.RegistrationServer，
// 内部把 pbv1 消息转为 internal/proto 消息后委托给 grpcx.RegistrationServer。
type RegistrationServer interface {
	Register(context.Context, *AgentInfo) (*RegisterResp, error)
	Heartbeat(context.Context, *HeartbeatReq) (*Empty, error)
	PullTasks(context.Context, *PullTasksReq) (*PullTasksResp, error)
	ReportResult(context.Context, *TaskResult) (*Empty, error)
	CancelTask(context.Context, *CancelTaskReq) (*Empty, error)
	PollCancels(context.Context, *PollCancelsReq) (*PollCancelsResp, error)
}

// UnimplementedRegistrationServer 必须被嵌入以获得 forward 兼容（新方法默认返回 Unimplemented）。
// JSON codec 为正式契约；grpcx.StubAdapter 显式实现全部 6 方法，不嵌入本结构体；
// 保留本结构体以符合 protoc-gen-go-grpc 标准输出格式，供未来直接实现 pbv1.RegistrationServer 时使用。
type UnimplementedRegistrationServer struct{}

func (UnimplementedRegistrationServer) Register(context.Context, *AgentInfo) (*RegisterResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Register not implemented")
}
func (UnimplementedRegistrationServer) Heartbeat(context.Context, *HeartbeatReq) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Heartbeat not implemented")
}
func (UnimplementedRegistrationServer) PullTasks(context.Context, *PullTasksReq) (*PullTasksResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PullTasks not implemented")
}
func (UnimplementedRegistrationServer) ReportResult(context.Context, *TaskResult) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReportResult not implemented")
}
func (UnimplementedRegistrationServer) CancelTask(context.Context, *CancelTaskReq) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CancelTask not implemented")
}
func (UnimplementedRegistrationServer) PollCancels(context.Context, *PollCancelsReq) (*PollCancelsResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PollCancels not implemented")
}

// RegisterRegistrationServer 把 srv 注册到 gRPC server，用生成的 ServiceDesc。
// JSON codec 为正式契约；controlplane 可调用 gs.RegisterService(&pbv1.Registration_ServiceDesc, grpcx.NewStubAdapter(impl)) 完成迁移。
func RegisterRegistrationServer(s *grpc.Server, srv RegistrationServer) {
	s.RegisterService(&Registration_ServiceDesc, srv)
}

// ===== ServiceDesc =====

// Registration_ServiceDesc 是生成的 gRPC 服务描述符。
// 与 internal/grpcx.Registration_ServiceDesc 同名同方法集，但 Handler 解码 pbv1 消息。
// JSON codec 为正式契约；此 ServiceDesc 保留供 buf breaking 守护和未来迁移使用，切换时只需在 server.go 改 RegisterService 的参数。
var Registration_ServiceDesc = grpc.ServiceDesc{
	ServiceName: Registration_ServiceName,
	HandlerType: (*RegistrationServer)(nil),
	Methods: []grpc.MethodDesc{
		{MethodName: "Register", Handler: _Registration_Register_Handler},
		{MethodName: "Heartbeat", Handler: _Registration_Heartbeat_Handler},
		{MethodName: "PullTasks", Handler: _Registration_PullTasks_Handler},
		{MethodName: "ReportResult", Handler: _Registration_ReportResult_Handler},
		{MethodName: "CancelTask", Handler: _Registration_CancelTask_Handler},
		{MethodName: "PollCancels", Handler: _Registration_PollCancels_Handler},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "opsmesh/v1/registration.proto",
}

// ===== 服务端分发 Handler（标准 gRPC 一元 Handler 写法）=====

func _Registration_Register_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AgentInfo)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RegistrationServer).Register(ctx, in)
	}
	info := &grpc.UnaryServerInfo{Server: srv, FullMethod: "/" + Registration_ServiceName + "/Register"}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RegistrationServer).Register(ctx, req.(*AgentInfo))
	}
	return interceptor(ctx, in, info, handler)
}

func _Registration_Heartbeat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HeartbeatReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RegistrationServer).Heartbeat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{Server: srv, FullMethod: "/" + Registration_ServiceName + "/Heartbeat"}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RegistrationServer).Heartbeat(ctx, req.(*HeartbeatReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Registration_PullTasks_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PullTasksReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RegistrationServer).PullTasks(ctx, in)
	}
	info := &grpc.UnaryServerInfo{Server: srv, FullMethod: "/" + Registration_ServiceName + "/PullTasks"}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RegistrationServer).PullTasks(ctx, req.(*PullTasksReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Registration_ReportResult_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TaskResult)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RegistrationServer).ReportResult(ctx, in)
	}
	info := &grpc.UnaryServerInfo{Server: srv, FullMethod: "/" + Registration_ServiceName + "/ReportResult"}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RegistrationServer).ReportResult(ctx, req.(*TaskResult))
	}
	return interceptor(ctx, in, info, handler)
}

func _Registration_CancelTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CancelTaskReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RegistrationServer).CancelTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{Server: srv, FullMethod: "/" + Registration_ServiceName + "/CancelTask"}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RegistrationServer).CancelTask(ctx, req.(*CancelTaskReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Registration_PollCancels_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PollCancelsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RegistrationServer).PollCancels(ctx, in)
	}
	info := &grpc.UnaryServerInfo{Server: srv, FullMethod: "/" + Registration_ServiceName + "/PollCancels"}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RegistrationServer).PollCancels(ctx, req.(*PollCancelsReq))
	}
	return interceptor(ctx, in, info, handler)
}

// ===== 客户端 stub =====

// RegistrationClient 是生成的 gRPC 客户端接口。
// JSON codec 为正式契约；agent 侧走 internal/agent/grpcclient.go（手写 JSON codec）；
// 切换到生成 stub 时用 NewRegistrationClient(conn) 构造客户端，走 protobuf codec。
type RegistrationClient interface {
	Register(ctx context.Context, in *AgentInfo, opts ...grpc.CallOption) (*RegisterResp, error)
	Heartbeat(ctx context.Context, in *HeartbeatReq, opts ...grpc.CallOption) (*Empty, error)
	PullTasks(ctx context.Context, in *PullTasksReq, opts ...grpc.CallOption) (*PullTasksResp, error)
	ReportResult(ctx context.Context, in *TaskResult, opts ...grpc.CallOption) (*Empty, error)
	CancelTask(ctx context.Context, in *CancelTaskReq, opts ...grpc.CallOption) (*Empty, error)
	PollCancels(ctx context.Context, in *PollCancelsReq, opts ...grpc.CallOption) (*PollCancelsResp, error)
}

// registrationClient 是 RegistrationClient 的实现，包装 grpc.ClientConn。
type registrationClient struct{ cc grpc.ClientConnInterface }

// NewRegistrationClient 构造生成的 gRPC 客户端。
func NewRegistrationClient(cc grpc.ClientConnInterface) RegistrationClient {
	return &registrationClient{cc}
}

func (c *registrationClient) Register(ctx context.Context, in *AgentInfo, opts ...grpc.CallOption) (*RegisterResp, error) {
	out := new(RegisterResp)
	err := c.cc.Invoke(ctx, "/"+Registration_ServiceName+"/Register", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *registrationClient) Heartbeat(ctx context.Context, in *HeartbeatReq, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/"+Registration_ServiceName+"/Heartbeat", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *registrationClient) PullTasks(ctx context.Context, in *PullTasksReq, opts ...grpc.CallOption) (*PullTasksResp, error) {
	out := new(PullTasksResp)
	err := c.cc.Invoke(ctx, "/"+Registration_ServiceName+"/PullTasks", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *registrationClient) ReportResult(ctx context.Context, in *TaskResult, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/"+Registration_ServiceName+"/ReportResult", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *registrationClient) CancelTask(ctx context.Context, in *CancelTaskReq, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/"+Registration_ServiceName+"/CancelTask", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *registrationClient) PollCancels(ctx context.Context, in *PollCancelsReq, opts ...grpc.CallOption) (*PollCancelsResp, error) {
	out := new(PollCancelsResp)
	err := c.cc.Invoke(ctx, "/"+Registration_ServiceName+"/PollCancels", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}
