// Code generated by protoc-gen-* — DO NOT EDIT MANUALLY.
// Source: proto/opsmesh/v1/registration.proto
//
// M3-3A protobuf 引入：agent↔控制面 注册通道的 IDL 契约。
// 与 internal/grpcx/service.go 手写 ServiceDesc 保持同名同方法集（opsmesh.v1.Registration），
// 兼容期两条路径并行：手写 JSON codec（默认）↔ 生成 stub（protobuf codec，灰度切换）。
// 破坏性变更由 buf breaking（FILE 策略）在 CI 守护，禁止删字段/改类型/改字段号。

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v5.27.0
// source: opsmesh/v1/registration.proto

package pbv1

import (
	context "context"

	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Registration_Register_FullMethodName     = "/opsmesh.v1.Registration/Register"
	Registration_Heartbeat_FullMethodName    = "/opsmesh.v1.Registration/Heartbeat"
	Registration_PullTasks_FullMethodName    = "/opsmesh.v1.Registration/PullTasks"
	Registration_ReportResult_FullMethodName = "/opsmesh.v1.Registration/ReportResult"
	Registration_CancelTask_FullMethodName   = "/opsmesh.v1.Registration/CancelTask"
	Registration_PollCancels_FullMethodName  = "/opsmesh.v1.Registration/PollCancels"
	Registration_ReportLogs_FullMethodName   = "/opsmesh.v1.Registration/ReportLogs"
)

// RegistrationClient is the client API for Registration service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Registration agent↔控制面 的注册通道服务。
// 服务名 opsmesh.v1.Registration（带版本前缀，破坏性变更可灰度）。
// 七个一元方法，无流式方法 —— 与 internal/grpcx.RegistrationServer 接口一一对应。
type RegistrationClient interface {
	Register(ctx context.Context, in *AgentInfo, opts ...grpc.CallOption) (*RegisterResp, error)
	Heartbeat(ctx context.Context, in *HeartbeatReq, opts ...grpc.CallOption) (*Empty, error)
	PullTasks(ctx context.Context, in *PullTasksReq, opts ...grpc.CallOption) (*PullTasksResp, error)
	ReportResult(ctx context.Context, in *TaskResult, opts ...grpc.CallOption) (*Empty, error)
	CancelTask(ctx context.Context, in *CancelTaskReq, opts ...grpc.CallOption) (*Empty, error)
	PollCancels(ctx context.Context, in *PollCancelsReq, opts ...grpc.CallOption) (*PollCancelsResp, error)
	ReportLogs(ctx context.Context, in *ReportLogsReq, opts ...grpc.CallOption) (*Empty, error)
}

type registrationClient struct {
	cc grpc.ClientConnInterface
}

func NewRegistrationClient(cc grpc.ClientConnInterface) RegistrationClient {
	return &registrationClient{cc}
}

func (c *registrationClient) Register(ctx context.Context, in *AgentInfo, opts ...grpc.CallOption) (*RegisterResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RegisterResp)
	err := c.cc.Invoke(ctx, Registration_Register_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *registrationClient) Heartbeat(ctx context.Context, in *HeartbeatReq, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, Registration_Heartbeat_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *registrationClient) PullTasks(ctx context.Context, in *PullTasksReq, opts ...grpc.CallOption) (*PullTasksResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PullTasksResp)
	err := c.cc.Invoke(ctx, Registration_PullTasks_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *registrationClient) ReportResult(ctx context.Context, in *TaskResult, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, Registration_ReportResult_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *registrationClient) CancelTask(ctx context.Context, in *CancelTaskReq, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, Registration_CancelTask_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *registrationClient) PollCancels(ctx context.Context, in *PollCancelsReq, opts ...grpc.CallOption) (*PollCancelsResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PollCancelsResp)
	err := c.cc.Invoke(ctx, Registration_PollCancels_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *registrationClient) ReportLogs(ctx context.Context, in *ReportLogsReq, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, Registration_ReportLogs_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RegistrationServer is the server API for Registration service.
//
// Registration agent↔控制面 的注册通道服务。
// 服务名 opsmesh.v1.Registration（带版本前缀，破坏性变更可灰度）。
// 七个一元方法，无流式方法 —— 与 internal/grpcx.RegistrationServer 接口一一对应。
type RegistrationServer interface {
	Register(context.Context, *AgentInfo) (*RegisterResp, error)
	Heartbeat(context.Context, *HeartbeatReq) (*Empty, error)
	PullTasks(context.Context, *PullTasksReq) (*PullTasksResp, error)
	ReportResult(context.Context, *TaskResult) (*Empty, error)
	CancelTask(context.Context, *CancelTaskReq) (*Empty, error)
	PollCancels(context.Context, *PollCancelsReq) (*PollCancelsResp, error)
	ReportLogs(context.Context, *ReportLogsReq) (*Empty, error)
}

// UnimplementedRegistrationServer can be embedded to have forward compatible implementations.
type UnimplementedRegistrationServer struct{}

func (UnimplementedRegistrationServer) Register(context.Context, *AgentInfo) (*RegisterResp, error) {
	return nil, status.Error(codes.Unimplemented, "method Register not implemented")
}
func (UnimplementedRegistrationServer) Heartbeat(context.Context, *HeartbeatReq) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method Heartbeat not implemented")
}
func (UnimplementedRegistrationServer) PullTasks(context.Context, *PullTasksReq) (*PullTasksResp, error) {
	return nil, status.Error(codes.Unimplemented, "method PullTasks not implemented")
}
func (UnimplementedRegistrationServer) ReportResult(context.Context, *TaskResult) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method ReportResult not implemented")
}
func (UnimplementedRegistrationServer) CancelTask(context.Context, *CancelTaskReq) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method CancelTask not implemented")
}
func (UnimplementedRegistrationServer) PollCancels(context.Context, *PollCancelsReq) (*PollCancelsResp, error) {
	return nil, status.Error(codes.Unimplemented, "method PollCancels not implemented")
}
func (UnimplementedRegistrationServer) ReportLogs(context.Context, *ReportLogsReq) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method ReportLogs not implemented")
}

// RegisterRegistrationServer registers a RegistrationServer on a grpc.Server.
func RegisterRegistrationServer(s *grpc.Server, srv RegistrationServer) {
	s.RegisterService(&Registration_ServiceDesc, srv)
}

func _Registration_Register_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AgentInfo)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RegistrationServer).Register(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Registration_Register_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RegistrationServer).Register(ctx, req.(*AgentInfo))
	}
	return interceptor(ctx, in, info, handler)
}

func _Registration_Heartbeat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HeartbeatReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RegistrationServer).Heartbeat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Registration_Heartbeat_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RegistrationServer).Heartbeat(ctx, req.(*HeartbeatReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Registration_PullTasks_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PullTasksReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RegistrationServer).PullTasks(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Registration_PullTasks_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RegistrationServer).PullTasks(ctx, req.(*PullTasksReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Registration_ReportResult_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TaskResult)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RegistrationServer).ReportResult(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Registration_ReportResult_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RegistrationServer).ReportResult(ctx, req.(*TaskResult))
	}
	return interceptor(ctx, in, info, handler)
}

func _Registration_CancelTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CancelTaskReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RegistrationServer).CancelTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Registration_CancelTask_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RegistrationServer).CancelTask(ctx, req.(*CancelTaskReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Registration_PollCancels_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PollCancelsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RegistrationServer).PollCancels(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Registration_PollCancels_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RegistrationServer).PollCancels(ctx, req.(*PollCancelsReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Registration_ReportLogs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReportLogsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RegistrationServer).ReportLogs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Registration_ReportLogs_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RegistrationServer).ReportLogs(ctx, req.(*ReportLogsReq))
	}
	return interceptor(ctx, in, info, handler)
}

// Registration_ServiceDesc is the grpc.ServiceDesc for Registration service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Registration_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "opsmesh.v1.Registration",
	HandlerType: (*RegistrationServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Register",
			Handler:    _Registration_Register_Handler,
		},
		{
			MethodName: "Heartbeat",
			Handler:    _Registration_Heartbeat_Handler,
		},
		{
			MethodName: "PullTasks",
			Handler:    _Registration_PullTasks_Handler,
		},
		{
			MethodName: "ReportResult",
			Handler:    _Registration_ReportResult_Handler,
		},
		{
			MethodName: "CancelTask",
			Handler:    _Registration_CancelTask_Handler,
		},
		{
			MethodName: "PollCancels",
			Handler:    _Registration_PollCancels_Handler,
		},
		{
			MethodName: "ReportLogs",
			Handler:    _Registration_ReportLogs_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "opsmesh/v1/registration.proto",
}
