// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.36.2
// source: alert.proto

package alertv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// AlertRule 告警规则。
type AlertRule struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	TenantId      string                 `protobuf:"bytes,2,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Metric        string                 `protobuf:"bytes,4,opt,name=metric,proto3" json:"metric,omitempty"`
	Op            string                 `protobuf:"bytes,5,opt,name=op,proto3" json:"op,omitempty"`
	Threshold     float64                `protobuf:"fixed64,6,opt,name=threshold,proto3" json:"threshold,omitempty"`
	Duration      int32                  `protobuf:"varint,7,opt,name=duration,proto3" json:"duration,omitempty"`
	Severity      string                 `protobuf:"bytes,8,opt,name=severity,proto3" json:"severity,omitempty"`
	Channels      []string               `protobuf:"bytes,9,rep,name=channels,proto3" json:"channels,omitempty"`
	Enabled       bool                   `protobuf:"varint,10,opt,name=enabled,proto3" json:"enabled,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,11,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,12,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AlertRule) Reset() {
	*x = AlertRule{}
	mi := &file_alert_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AlertRule) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AlertRule) ProtoMessage() {}

func (x *AlertRule) ProtoReflect() protoreflect.Message {
	mi := &file_alert_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AlertRule.ProtoReflect.Descriptor instead.
func (*AlertRule) Descriptor() ([]byte, []int) {
	return file_alert_proto_rawDescGZIP(), []int{0}
}

func (x *AlertRule) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *AlertRule) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *AlertRule) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AlertRule) GetMetric() string {
	if x != nil {
		return x.Metric
	}
	return ""
}

func (x *AlertRule) GetOp() string {
	if x != nil {
		return x.Op
	}
	return ""
}

func (x *AlertRule) GetThreshold() float64 {
	if x != nil {
		return x.Threshold
	}
	return 0
}

func (x *AlertRule) GetDuration() int32 {
	if x != nil {
		return x.Duration
	}
	return 0
}

func (x *AlertRule) GetSeverity() string {
	if x != nil {
		return x.Severity
	}
	return ""
}

func (x *AlertRule) GetChannels() []string {
	if x != nil {
		return x.Channels
	}
	return nil
}

func (x *AlertRule) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *AlertRule) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *AlertRule) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

// Alert 告警事件。
type Alert struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	Id        string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	TenantId  string                 `protobuf:"bytes,2,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	RuleId    string                 `protobuf:"bytes,3,opt,name=rule_id,json=ruleId,proto3" json:"rule_id,omitempty"`
	RuleName  string                 `protobuf:"bytes,4,opt,name=rule_name,json=ruleName,proto3" json:"rule_name,omitempty"`
	Severity  string                 `protobuf:"bytes,5,opt,name=severity,proto3" json:"severity,omitempty"`
	Message   string                 `protobuf:"bytes,6,opt,name=message,proto3" json:"message,omitempty"`
	Values    map[string]float64     `protobuf:"bytes,7,rep,name=values,proto3" json:"values,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"fixed64,2,opt,name=value"`
	Status    string                 `protobuf:"bytes,8,opt,name=status,proto3" json:"status,omitempty"` // firing|acknowledged|silenced|resolved
	FiredAt   *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=fired_at,json=firedAt,proto3" json:"fired_at,omitempty"`
	UpdatedAt *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	// device_id / metric 是告警最基本的两个事实——"哪台设备、哪个指标"。
	// 修前 Alert 消息里根本没有这两个字段（store 里有），于是 gRPC 侧列出告警时
	// 客户看到的是"有个告警"但不知道是谁的；按指标查告警也无从下手。
	DeviceId      string `protobuf:"bytes,11,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	Metric        string `protobuf:"bytes,12,opt,name=metric,proto3" json:"metric,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Alert) Reset() {
	*x = Alert{}
	mi := &file_alert_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Alert) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Alert) ProtoMessage() {}

func (x *Alert) ProtoReflect() protoreflect.Message {
	mi := &file_alert_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Alert.ProtoReflect.Descriptor instead.
func (*Alert) Descriptor() ([]byte, []int) {
	return file_alert_proto_rawDescGZIP(), []int{1}
}

func (x *Alert) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Alert) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *Alert) GetRuleId() string {
	if x != nil {
		return x.RuleId
	}
	return ""
}

func (x *Alert) GetRuleName() string {
	if x != nil {
		return x.RuleName
	}
	return ""
}

func (x *Alert) GetSeverity() string {
	if x != nil {
		return x.Severity
	}
	return ""
}

func (x *Alert) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *Alert) GetValues() map[string]float64 {
	if x != nil {
		return x.Values
	}
	return nil
}

func (x *Alert) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Alert) GetFiredAt() *timestamppb.Timestamp {
	if x != nil {
		return x.FiredAt
	}
	return nil
}

func (x *Alert) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *Alert) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *Alert) GetMetric() string {
	if x != nil {
		return x.Metric
	}
	return ""
}

// CreateRuleRequest 创建规则请求。
type CreateRuleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Rule          *AlertRule             `protobuf:"bytes,1,opt,name=rule,proto3" json:"rule,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateRuleRequest) Reset() {
	*x = CreateRuleRequest{}
	mi := &file_alert_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateRuleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRuleRequest) ProtoMessage() {}

func (x *CreateRuleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_alert_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRuleRequest.ProtoReflect.Descriptor instead.
func (*CreateRuleRequest) Descriptor() ([]byte, []int) {
	return file_alert_proto_rawDescGZIP(), []int{2}
}

func (x *CreateRuleRequest) GetRule() *AlertRule {
	if x != nil {
		return x.Rule
	}
	return nil
}

// GetRuleRequest 获取规则请求。
type GetRuleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRuleRequest) Reset() {
	*x = GetRuleRequest{}
	mi := &file_alert_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRuleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRuleRequest) ProtoMessage() {}

func (x *GetRuleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_alert_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRuleRequest.ProtoReflect.Descriptor instead.
func (*GetRuleRequest) Descriptor() ([]byte, []int) {
	return file_alert_proto_rawDescGZIP(), []int{3}
}

func (x *GetRuleRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

// UpdateRuleRequest 更新规则请求。
type UpdateRuleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Rule          *AlertRule             `protobuf:"bytes,1,opt,name=rule,proto3" json:"rule,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateRuleRequest) Reset() {
	*x = UpdateRuleRequest{}
	mi := &file_alert_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateRuleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateRuleRequest) ProtoMessage() {}

func (x *UpdateRuleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_alert_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateRuleRequest.ProtoReflect.Descriptor instead.
func (*UpdateRuleRequest) Descriptor() ([]byte, []int) {
	return file_alert_proto_rawDescGZIP(), []int{4}
}

func (x *UpdateRuleRequest) GetRule() *AlertRule {
	if x != nil {
		return x.Rule
	}
	return nil
}

// DeleteRuleRequest 删除规则请求。
type DeleteRuleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteRuleRequest) Reset() {
	*x = DeleteRuleRequest{}
	mi := &file_alert_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteRuleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRuleRequest) ProtoMessage() {}

func (x *DeleteRuleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_alert_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteRuleRequest.ProtoReflect.Descriptor instead.
func (*DeleteRuleRequest) Descriptor() ([]byte, []int) {
	return file_alert_proto_rawDescGZIP(), []int{5}
}

func (x *DeleteRuleRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

// ListRulesResponse 规则列表响应。
type ListRulesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Rules         []*AlertRule           `protobuf:"bytes,1,rep,name=rules,proto3" json:"rules,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRulesResponse) Reset() {
	*x = ListRulesResponse{}
	mi := &file_alert_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRulesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRulesResponse) ProtoMessage() {}

func (x *ListRulesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_alert_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRulesResponse.ProtoReflect.Descriptor instead.
func (*ListRulesResponse) Descriptor() ([]byte, []int) {
	return file_alert_proto_rawDescGZIP(), []int{6}
}

func (x *ListRulesResponse) GetRules() []*AlertRule {
	if x != nil {
		return x.Rules
	}
	return nil
}

// EvaluateRequest 评估请求。
type EvaluateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantId      string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	DeviceId      string                 `protobuf:"bytes,2,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	Metrics       map[string]float64     `protobuf:"bytes,3,rep,name=metrics,proto3" json:"metrics,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"fixed64,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EvaluateRequest) Reset() {
	*x = EvaluateRequest{}
	mi := &file_alert_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EvaluateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EvaluateRequest) ProtoMessage() {}

func (x *EvaluateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_alert_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EvaluateRequest.ProtoReflect.Descriptor instead.
func (*EvaluateRequest) Descriptor() ([]byte, []int) {
	return file_alert_proto_rawDescGZIP(), []int{7}
}

func (x *EvaluateRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *EvaluateRequest) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *EvaluateRequest) GetMetrics() map[string]float64 {
	if x != nil {
		return x.Metrics
	}
	return nil
}

// EvaluateResponse 评估响应。
//
// 光返回 alerts 是不够的：修前引擎根本不读指标（见 internal/engine），
// "0 条告警"既可能是"读数都没超阈值"也可能是"你没给读数"，两者对客户完全不同。
// 因此把评估面本身也作为契约输出。
type EvaluateResponse struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	Alerts []*Alert               `protobuf:"bytes,1,rep,name=alerts,proto3" json:"alerts,omitempty"`
	// evaluated_rules：真正拿到读数并完成判定的规则条数。
	EvaluatedRules int32 `protobuf:"varint,2,opt,name=evaluated_rules,json=evaluatedRules,proto3" json:"evaluated_rules,omitempty"`
	// pending_rules：已命中但还没满足 duration（"for"）的规则 ID。
	PendingRules []string `protobuf:"bytes,3,rep,name=pending_rules,json=pendingRules,proto3" json:"pending_rules,omitempty"`
	// no_data_rules：引用了本次没有读数的指标、因此无法判定的规则 ID。
	// ⚠️ "没数据"不等于"没命中"，把它混进 alerts=空就是假装健康。
	NoDataRules []string `protobuf:"bytes,4,rep,name=no_data_rules,json=noDataRules,proto3" json:"no_data_rules,omitempty"`
	// invalid_rules：规则本身配错（如操作符不认识）而无法判定的规则 ID。
	InvalidRules []string `protobuf:"bytes,5,rep,name=invalid_rules,json=invalidRules,proto3" json:"invalid_rules,omitempty"`
	// metrics_supplied：本次请求带来的读数条数。为 0 而规则又不是 0 条时，
	// 结论必然全是 no_data——把这个数字回给调用方，"你忘了传指标"才看得见。
	MetricsSupplied int32 `protobuf:"varint,6,opt,name=metrics_supplied,json=metricsSupplied,proto3" json:"metrics_supplied,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *EvaluateResponse) Reset() {
	*x = EvaluateResponse{}
	mi := &file_alert_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EvaluateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EvaluateResponse) ProtoMessage() {}

func (x *EvaluateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_alert_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EvaluateResponse.ProtoReflect.Descriptor instead.
func (*EvaluateResponse) Descriptor() ([]byte, []int) {
	return file_alert_proto_rawDescGZIP(), []int{8}
}

func (x *EvaluateResponse) GetAlerts() []*Alert {
	if x != nil {
		return x.Alerts
	}
	return nil
}

func (x *EvaluateResponse) GetEvaluatedRules() int32 {
	if x != nil {
		return x.EvaluatedRules
	}
	return 0
}

func (x *EvaluateResponse) GetPendingRules() []string {
	if x != nil {
		return x.PendingRules
	}
	return nil
}

func (x *EvaluateResponse) GetNoDataRules() []string {
	if x != nil {
		return x.NoDataRules
	}
	return nil
}

func (x *EvaluateResponse) GetInvalidRules() []string {
	if x != nil {
		return x.InvalidRules
	}
	return nil
}

func (x *EvaluateResponse) GetMetricsSupplied() int32 {
	if x != nil {
		return x.MetricsSupplied
	}
	return 0
}

// GetAlertRequest 获取告警请求。
type GetAlertRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAlertRequest) Reset() {
	*x = GetAlertRequest{}
	mi := &file_alert_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAlertRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAlertRequest) ProtoMessage() {}

func (x *GetAlertRequest) ProtoReflect() protoreflect.Message {
	mi := &file_alert_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAlertRequest.ProtoReflect.Descriptor instead.
func (*GetAlertRequest) Descriptor() ([]byte, []int) {
	return file_alert_proto_rawDescGZIP(), []int{9}
}

func (x *GetAlertRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

// ListAlertsRequest 列出告警请求。
type ListAlertsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantId      string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	Limit         int32                  `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAlertsRequest) Reset() {
	*x = ListAlertsRequest{}
	mi := &file_alert_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAlertsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAlertsRequest) ProtoMessage() {}

func (x *ListAlertsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_alert_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAlertsRequest.ProtoReflect.Descriptor instead.
func (*ListAlertsRequest) Descriptor() ([]byte, []int) {
	return file_alert_proto_rawDescGZIP(), []int{10}
}

func (x *ListAlertsRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *ListAlertsRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ListAlertsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

// ListAlertsResponse 告警列表响应。
type ListAlertsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Alerts        []*Alert               `protobuf:"bytes,1,rep,name=alerts,proto3" json:"alerts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAlertsResponse) Reset() {
	*x = ListAlertsResponse{}
	mi := &file_alert_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAlertsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAlertsResponse) ProtoMessage() {}

func (x *ListAlertsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_alert_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAlertsResponse.ProtoReflect.Descriptor instead.
func (*ListAlertsResponse) Descriptor() ([]byte, []int) {
	return file_alert_proto_rawDescGZIP(), []int{11}
}

func (x *ListAlertsResponse) GetAlerts() []*Alert {
	if x != nil {
		return x.Alerts
	}
	return nil
}

// AckAlertRequest 确认告警请求。
type AckAlertRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AckAlertRequest) Reset() {
	*x = AckAlertRequest{}
	mi := &file_alert_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AckAlertRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AckAlertRequest) ProtoMessage() {}

func (x *AckAlertRequest) ProtoReflect() protoreflect.Message {
	mi := &file_alert_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AckAlertRequest.ProtoReflect.Descriptor instead.
func (*AckAlertRequest) Descriptor() ([]byte, []int) {
	return file_alert_proto_rawDescGZIP(), []int{12}
}

func (x *AckAlertRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

// SilenceAlertRequest 静默告警请求。
type SilenceAlertRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	DurationMinutes int32                  `protobuf:"varint,2,opt,name=duration_minutes,json=durationMinutes,proto3" json:"duration_minutes,omitempty"`
	Comment         string                 `protobuf:"bytes,3,opt,name=comment,proto3" json:"comment,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *SilenceAlertRequest) Reset() {
	*x = SilenceAlertRequest{}
	mi := &file_alert_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SilenceAlertRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SilenceAlertRequest) ProtoMessage() {}

func (x *SilenceAlertRequest) ProtoReflect() protoreflect.Message {
	mi := &file_alert_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SilenceAlertRequest.ProtoReflect.Descriptor instead.
func (*SilenceAlertRequest) Descriptor() ([]byte, []int) {
	return file_alert_proto_rawDescGZIP(), []int{13}
}

func (x *SilenceAlertRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *SilenceAlertRequest) GetDurationMinutes() int32 {
	if x != nil {
		return x.DurationMinutes
	}
	return 0
}

func (x *SilenceAlertRequest) GetComment() string {
	if x != nil {
		return x.Comment
	}
	return ""
}

// ResolveAlertRequest 解决告警请求。
type ResolveAlertRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResolveAlertRequest) Reset() {
	*x = ResolveAlertRequest{}
	mi := &file_alert_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResolveAlertRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResolveAlertRequest) ProtoMessage() {}

func (x *ResolveAlertRequest) ProtoReflect() protoreflect.Message {
	mi := &file_alert_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResolveAlertRequest.ProtoReflect.Descriptor instead.
func (*ResolveAlertRequest) Descriptor() ([]byte, []int) {
	return file_alert_proto_rawDescGZIP(), []int{14}
}

func (x *ResolveAlertRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

var File_alert_proto protoreflect.FileDescriptor

const file_alert_proto_rawDesc = "" +
	"\n" +
	"\valert.proto\x12\x10opsmesh.alert.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1bgoogle/protobuf/empty.proto\"\xf6\x02\n" +
	"\tAlertRule\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1b\n" +
	"\ttenant_id\x18\x02 \x01(\tR\btenantId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x16\n" +
	"\x06metric\x18\x04 \x01(\tR\x06metric\x12\x0e\n" +
	"\x02op\x18\x05 \x01(\tR\x02op\x12\x1c\n" +
	"\tthreshold\x18\x06 \x01(\x01R\tthreshold\x12\x1a\n" +
	"\bduration\x18\a \x01(\x05R\bduration\x12\x1a\n" +
	"\bseverity\x18\b \x01(\tR\bseverity\x12\x1a\n" +
	"\bchannels\x18\t \x03(\tR\bchannels\x12\x18\n" +
	"\aenabled\x18\n" +
	" \x01(\bR\aenabled\x129\n" +
	"\n" +
	"created_at\x18\v \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\f \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"\xd7\x03\n" +
	"\x05Alert\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1b\n" +
	"\ttenant_id\x18\x02 \x01(\tR\btenantId\x12\x17\n" +
	"\arule_id\x18\x03 \x01(\tR\x06ruleId\x12\x1b\n" +
	"\trule_name\x18\x04 \x01(\tR\bruleName\x12\x1a\n" +
	"\bseverity\x18\x05 \x01(\tR\bseverity\x12\x18\n" +
	"\amessage\x18\x06 \x01(\tR\amessage\x12;\n" +
	"\x06values\x18\a \x03(\v2#.opsmesh.alert.v1.Alert.ValuesEntryR\x06values\x12\x16\n" +
	"\x06status\x18\b \x01(\tR\x06status\x125\n" +
	"\bfired_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\afiredAt\x129\n" +
	"\n" +
	"updated_at\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x12\x1b\n" +
	"\tdevice_id\x18\v \x01(\tR\bdeviceId\x12\x16\n" +
	"\x06metric\x18\f \x01(\tR\x06metric\x1a9\n" +
	"\vValuesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x01R\x05value:\x028\x01\"D\n" +
	"\x11CreateRuleRequest\x12/\n" +
	"\x04rule\x18\x01 \x01(\v2\x1b.opsmesh.alert.v1.AlertRuleR\x04rule\" \n" +
	"\x0eGetRuleRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"D\n" +
	"\x11UpdateRuleRequest\x12/\n" +
	"\x04rule\x18\x01 \x01(\v2\x1b.opsmesh.alert.v1.AlertRuleR\x04rule\"#\n" +
	"\x11DeleteRuleRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"F\n" +
	"\x11ListRulesResponse\x121\n" +
	"\x05rules\x18\x01 \x03(\v2\x1b.opsmesh.alert.v1.AlertRuleR\x05rules\"\xd1\x01\n" +
	"\x0fEvaluateRequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12\x1b\n" +
	"\tdevice_id\x18\x02 \x01(\tR\bdeviceId\x12H\n" +
	"\ametrics\x18\x03 \x03(\v2..opsmesh.alert.v1.EvaluateRequest.MetricsEntryR\ametrics\x1a:\n" +
	"\fMetricsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x01R\x05value:\x028\x01\"\x85\x02\n" +
	"\x10EvaluateResponse\x12/\n" +
	"\x06alerts\x18\x01 \x03(\v2\x17.opsmesh.alert.v1.AlertR\x06alerts\x12'\n" +
	"\x0fevaluated_rules\x18\x02 \x01(\x05R\x0eevaluatedRules\x12#\n" +
	"\rpending_rules\x18\x03 \x03(\tR\fpendingRules\x12\"\n" +
	"\rno_data_rules\x18\x04 \x03(\tR\vnoDataRules\x12#\n" +
	"\rinvalid_rules\x18\x05 \x03(\tR\finvalidRules\x12)\n" +
	"\x10metrics_supplied\x18\x06 \x01(\x05R\x0fmetricsSupplied\"!\n" +
	"\x0fGetAlertRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"^\n" +
	"\x11ListAlertsRequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\x05R\x05limit\"E\n" +
	"\x12ListAlertsResponse\x12/\n" +
	"\x06alerts\x18\x01 \x03(\v2\x17.opsmesh.alert.v1.AlertR\x06alerts\"!\n" +
	"\x0fAckAlertRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"j\n" +
	"\x13SilenceAlertRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12)\n" +
	"\x10duration_minutes\x18\x02 \x01(\x05R\x0fdurationMinutes\x12\x18\n" +
	"\acomment\x18\x03 \x01(\tR\acomment\"%\n" +
	"\x13ResolveAlertRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id2\xe6\x06\n" +
	"\fAlertService\x12N\n" +
	"\n" +
	"CreateRule\x12#.opsmesh.alert.v1.CreateRuleRequest\x1a\x1b.opsmesh.alert.v1.AlertRule\x12H\n" +
	"\aGetRule\x12 .opsmesh.alert.v1.GetRuleRequest\x1a\x1b.opsmesh.alert.v1.AlertRule\x12H\n" +
	"\tListRules\x12\x16.google.protobuf.Empty\x1a#.opsmesh.alert.v1.ListRulesResponse\x12N\n" +
	"\n" +
	"UpdateRule\x12#.opsmesh.alert.v1.UpdateRuleRequest\x1a\x1b.opsmesh.alert.v1.AlertRule\x12I\n" +
	"\n" +
	"DeleteRule\x12#.opsmesh.alert.v1.DeleteRuleRequest\x1a\x16.google.protobuf.Empty\x12Q\n" +
	"\bEvaluate\x12!.opsmesh.alert.v1.EvaluateRequest\x1a\".opsmesh.alert.v1.EvaluateResponse\x12F\n" +
	"\bGetAlert\x12!.opsmesh.alert.v1.GetAlertRequest\x1a\x17.opsmesh.alert.v1.Alert\x12W\n" +
	"\n" +
	"ListAlerts\x12#.opsmesh.alert.v1.ListAlertsRequest\x1a$.opsmesh.alert.v1.ListAlertsResponse\x12E\n" +
	"\bAckAlert\x12!.opsmesh.alert.v1.AckAlertRequest\x1a\x16.google.protobuf.Empty\x12M\n" +
	"\fSilenceAlert\x12%.opsmesh.alert.v1.SilenceAlertRequest\x1a\x16.google.protobuf.Empty\x12M\n" +
	"\fResolveAlert\x12%.opsmesh.alert.v1.ResolveAlertRequest\x1a\x16.google.protobuf.EmptyBEZCgithub.com/Levango7/OpsMesh/services/alert-svc/api/proto/v1;alertv1b\x06proto3"

var (
	file_alert_proto_rawDescOnce sync.Once
	file_alert_proto_rawDescData []byte
)

func file_alert_proto_rawDescGZIP() []byte {
	file_alert_proto_rawDescOnce.Do(func() {
		file_alert_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_alert_proto_rawDesc), len(file_alert_proto_rawDesc)))
	})
	return file_alert_proto_rawDescData
}

var file_alert_proto_msgTypes = make([]protoimpl.MessageInfo, 17)
var file_alert_proto_goTypes = []any{
	(*AlertRule)(nil),             // 0: opsmesh.alert.v1.AlertRule
	(*Alert)(nil),                 // 1: opsmesh.alert.v1.Alert
	(*CreateRuleRequest)(nil),     // 2: opsmesh.alert.v1.CreateRuleRequest
	(*GetRuleRequest)(nil),        // 3: opsmesh.alert.v1.GetRuleRequest
	(*UpdateRuleRequest)(nil),     // 4: opsmesh.alert.v1.UpdateRuleRequest
	(*DeleteRuleRequest)(nil),     // 5: opsmesh.alert.v1.DeleteRuleRequest
	(*ListRulesResponse)(nil),     // 6: opsmesh.alert.v1.ListRulesResponse
	(*EvaluateRequest)(nil),       // 7: opsmesh.alert.v1.EvaluateRequest
	(*EvaluateResponse)(nil),      // 8: opsmesh.alert.v1.EvaluateResponse
	(*GetAlertRequest)(nil),       // 9: opsmesh.alert.v1.GetAlertRequest
	(*ListAlertsRequest)(nil),     // 10: opsmesh.alert.v1.ListAlertsRequest
	(*ListAlertsResponse)(nil),    // 11: opsmesh.alert.v1.ListAlertsResponse
	(*AckAlertRequest)(nil),       // 12: opsmesh.alert.v1.AckAlertRequest
	(*SilenceAlertRequest)(nil),   // 13: opsmesh.alert.v1.SilenceAlertRequest
	(*ResolveAlertRequest)(nil),   // 14: opsmesh.alert.v1.ResolveAlertRequest
	nil,                           // 15: opsmesh.alert.v1.Alert.ValuesEntry
	nil,                           // 16: opsmesh.alert.v1.EvaluateRequest.MetricsEntry
	(*timestamppb.Timestamp)(nil), // 17: google.protobuf.Timestamp
	(*emptypb.Empty)(nil),         // 18: google.protobuf.Empty
}
var file_alert_proto_depIdxs = []int32{
	17, // 0: opsmesh.alert.v1.AlertRule.created_at:type_name -> google.protobuf.Timestamp
	17, // 1: opsmesh.alert.v1.AlertRule.updated_at:type_name -> google.protobuf.Timestamp
	15, // 2: opsmesh.alert.v1.Alert.values:type_name -> opsmesh.alert.v1.Alert.ValuesEntry
	17, // 3: opsmesh.alert.v1.Alert.fired_at:type_name -> google.protobuf.Timestamp
	17, // 4: opsmesh.alert.v1.Alert.updated_at:type_name -> google.protobuf.Timestamp
	0,  // 5: opsmesh.alert.v1.CreateRuleRequest.rule:type_name -> opsmesh.alert.v1.AlertRule
	0,  // 6: opsmesh.alert.v1.UpdateRuleRequest.rule:type_name -> opsmesh.alert.v1.AlertRule
	0,  // 7: opsmesh.alert.v1.ListRulesResponse.rules:type_name -> opsmesh.alert.v1.AlertRule
	16, // 8: opsmesh.alert.v1.EvaluateRequest.metrics:type_name -> opsmesh.alert.v1.EvaluateRequest.MetricsEntry
	1,  // 9: opsmesh.alert.v1.EvaluateResponse.alerts:type_name -> opsmesh.alert.v1.Alert
	1,  // 10: opsmesh.alert.v1.ListAlertsResponse.alerts:type_name -> opsmesh.alert.v1.Alert
	2,  // 11: opsmesh.alert.v1.AlertService.CreateRule:input_type -> opsmesh.alert.v1.CreateRuleRequest
	3,  // 12: opsmesh.alert.v1.AlertService.GetRule:input_type -> opsmesh.alert.v1.GetRuleRequest
	18, // 13: opsmesh.alert.v1.AlertService.ListRules:input_type -> google.protobuf.Empty
	4,  // 14: opsmesh.alert.v1.AlertService.UpdateRule:input_type -> opsmesh.alert.v1.UpdateRuleRequest
	5,  // 15: opsmesh.alert.v1.AlertService.DeleteRule:input_type -> opsmesh.alert.v1.DeleteRuleRequest
	7,  // 16: opsmesh.alert.v1.AlertService.Evaluate:input_type -> opsmesh.alert.v1.EvaluateRequest
	9,  // 17: opsmesh.alert.v1.AlertService.GetAlert:input_type -> opsmesh.alert.v1.GetAlertRequest
	10, // 18: opsmesh.alert.v1.AlertService.ListAlerts:input_type -> opsmesh.alert.v1.ListAlertsRequest
	12, // 19: opsmesh.alert.v1.AlertService.AckAlert:input_type -> opsmesh.alert.v1.AckAlertRequest
	13, // 20: opsmesh.alert.v1.AlertService.SilenceAlert:input_type -> opsmesh.alert.v1.SilenceAlertRequest
	14, // 21: opsmesh.alert.v1.AlertService.ResolveAlert:input_type -> opsmesh.alert.v1.ResolveAlertRequest
	0,  // 22: opsmesh.alert.v1.AlertService.CreateRule:output_type -> opsmesh.alert.v1.AlertRule
	0,  // 23: opsmesh.alert.v1.AlertService.GetRule:output_type -> opsmesh.alert.v1.AlertRule
	6,  // 24: opsmesh.alert.v1.AlertService.ListRules:output_type -> opsmesh.alert.v1.ListRulesResponse
	0,  // 25: opsmesh.alert.v1.AlertService.UpdateRule:output_type -> opsmesh.alert.v1.AlertRule
	18, // 26: opsmesh.alert.v1.AlertService.DeleteRule:output_type -> google.protobuf.Empty
	8,  // 27: opsmesh.alert.v1.AlertService.Evaluate:output_type -> opsmesh.alert.v1.EvaluateResponse
	1,  // 28: opsmesh.alert.v1.AlertService.GetAlert:output_type -> opsmesh.alert.v1.Alert
	11, // 29: opsmesh.alert.v1.AlertService.ListAlerts:output_type -> opsmesh.alert.v1.ListAlertsResponse
	18, // 30: opsmesh.alert.v1.AlertService.AckAlert:output_type -> google.protobuf.Empty
	18, // 31: opsmesh.alert.v1.AlertService.SilenceAlert:output_type -> google.protobuf.Empty
	18, // 32: opsmesh.alert.v1.AlertService.ResolveAlert:output_type -> google.protobuf.Empty
	22, // [22:33] is the sub-list for method output_type
	11, // [11:22] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_alert_proto_init() }
func file_alert_proto_init() {
	if File_alert_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_alert_proto_rawDesc), len(file_alert_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   17,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_alert_proto_goTypes,
		DependencyIndexes: file_alert_proto_depIdxs,
		MessageInfos:      file_alert_proto_msgTypes,
	}.Build()
	File_alert_proto = out.File
	file_alert_proto_goTypes = nil
	file_alert_proto_depIdxs = nil
}
