// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.36.2
// source: config.proto

package configv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ConfigItem represents a configuration entry.
type ConfigItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	TenantId      string                 `protobuf:"bytes,2,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	Key           string                 `protobuf:"bytes,3,opt,name=key,proto3" json:"key,omitempty"`
	Value         string                 `protobuf:"bytes,4,opt,name=value,proto3" json:"value,omitempty"`
	Format        string                 `protobuf:"bytes,5,opt,name=format,proto3" json:"format,omitempty"`
	Version       int32                  `protobuf:"varint,6,opt,name=version,proto3" json:"version,omitempty"`
	Description   string                 `protobuf:"bytes,7,opt,name=description,proto3" json:"description,omitempty"`
	UpdatedBy     string                 `protobuf:"bytes,8,opt,name=updated_by,json=updatedBy,proto3" json:"updated_by,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfigItem) Reset() {
	*x = ConfigItem{}
	mi := &file_config_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigItem) ProtoMessage() {}

func (x *ConfigItem) ProtoReflect() protoreflect.Message {
	mi := &file_config_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigItem.ProtoReflect.Descriptor instead.
func (*ConfigItem) Descriptor() ([]byte, []int) {
	return file_config_proto_rawDescGZIP(), []int{0}
}

func (x *ConfigItem) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ConfigItem) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *ConfigItem) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *ConfigItem) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *ConfigItem) GetFormat() string {
	if x != nil {
		return x.Format
	}
	return ""
}

func (x *ConfigItem) GetVersion() int32 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *ConfigItem) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *ConfigItem) GetUpdatedBy() string {
	if x != nil {
		return x.UpdatedBy
	}
	return ""
}

func (x *ConfigItem) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *ConfigItem) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

// SecretItem represents a secret (internal, contains plaintext value).
type SecretItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	TenantId      string                 `protobuf:"bytes,2,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	Key           string                 `protobuf:"bytes,3,opt,name=key,proto3" json:"key,omitempty"`
	Value         string                 `protobuf:"bytes,4,opt,name=value,proto3" json:"value,omitempty"`
	KeyType       string                 `protobuf:"bytes,5,opt,name=key_type,json=keyType,proto3" json:"key_type,omitempty"`
	Version       int32                  `protobuf:"varint,6,opt,name=version,proto3" json:"version,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SecretItem) Reset() {
	*x = SecretItem{}
	mi := &file_config_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SecretItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SecretItem) ProtoMessage() {}

func (x *SecretItem) ProtoReflect() protoreflect.Message {
	mi := &file_config_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SecretItem.ProtoReflect.Descriptor instead.
func (*SecretItem) Descriptor() ([]byte, []int) {
	return file_config_proto_rawDescGZIP(), []int{1}
}

func (x *SecretItem) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *SecretItem) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *SecretItem) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *SecretItem) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *SecretItem) GetKeyType() string {
	if x != nil {
		return x.KeyType
	}
	return ""
}

func (x *SecretItem) GetVersion() int32 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *SecretItem) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *SecretItem) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

// SecretMeta represents secret metadata (external, no value).
type SecretMeta struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	TenantId      string                 `protobuf:"bytes,2,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	Key           string                 `protobuf:"bytes,3,opt,name=key,proto3" json:"key,omitempty"`
	KeyType       string                 `protobuf:"bytes,4,opt,name=key_type,json=keyType,proto3" json:"key_type,omitempty"`
	Version       int32                  `protobuf:"varint,5,opt,name=version,proto3" json:"version,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SecretMeta) Reset() {
	*x = SecretMeta{}
	mi := &file_config_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SecretMeta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SecretMeta) ProtoMessage() {}

func (x *SecretMeta) ProtoReflect() protoreflect.Message {
	mi := &file_config_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SecretMeta.ProtoReflect.Descriptor instead.
func (*SecretMeta) Descriptor() ([]byte, []int) {
	return file_config_proto_rawDescGZIP(), []int{2}
}

func (x *SecretMeta) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *SecretMeta) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *SecretMeta) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *SecretMeta) GetKeyType() string {
	if x != nil {
		return x.KeyType
	}
	return ""
}

func (x *SecretMeta) GetVersion() int32 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *SecretMeta) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *SecretMeta) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

// NotifyChannel represents a notification channel.
type NotifyChannel struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	TenantId      string                 `protobuf:"bytes,2,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Type          string                 `protobuf:"bytes,4,opt,name=type,proto3" json:"type,omitempty"`
	Config        string                 `protobuf:"bytes,5,opt,name=config,proto3" json:"config,omitempty"`
	Enabled       bool                   `protobuf:"varint,6,opt,name=enabled,proto3" json:"enabled,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NotifyChannel) Reset() {
	*x = NotifyChannel{}
	mi := &file_config_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NotifyChannel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NotifyChannel) ProtoMessage() {}

func (x *NotifyChannel) ProtoReflect() protoreflect.Message {
	mi := &file_config_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NotifyChannel.ProtoReflect.Descriptor instead.
func (*NotifyChannel) Descriptor() ([]byte, []int) {
	return file_config_proto_rawDescGZIP(), []int{3}
}

func (x *NotifyChannel) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *NotifyChannel) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *NotifyChannel) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *NotifyChannel) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *NotifyChannel) GetConfig() string {
	if x != nil {
		return x.Config
	}
	return ""
}

func (x *NotifyChannel) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *NotifyChannel) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *NotifyChannel) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

// ConfigTemplate represents a configuration template.
type ConfigTemplate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	TenantId      string                 `protobuf:"bytes,2,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	Content       string                 `protobuf:"bytes,5,opt,name=content,proto3" json:"content,omitempty"`
	Variables     map[string]string      `protobuf:"bytes,6,rep,name=variables,proto3" json:"variables,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfigTemplate) Reset() {
	*x = ConfigTemplate{}
	mi := &file_config_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigTemplate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigTemplate) ProtoMessage() {}

func (x *ConfigTemplate) ProtoReflect() protoreflect.Message {
	mi := &file_config_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigTemplate.ProtoReflect.Descriptor instead.
func (*ConfigTemplate) Descriptor() ([]byte, []int) {
	return file_config_proto_rawDescGZIP(), []int{4}
}

func (x *ConfigTemplate) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ConfigTemplate) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *ConfigTemplate) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ConfigTemplate) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *ConfigTemplate) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *ConfigTemplate) GetVariables() map[string]string {
	if x != nil {
		return x.Variables
	}
	return nil
}

func (x *ConfigTemplate) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *ConfigTemplate) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type GetConfigRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantId      string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	Key           string                 `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetConfigRequest) Reset() {
	*x = GetConfigRequest{}
	mi := &file_config_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetConfigRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetConfigRequest) ProtoMessage() {}

func (x *GetConfigRequest) ProtoReflect() protoreflect.Message {
	mi := &file_config_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetConfigRequest.ProtoReflect.Descriptor instead.
func (*GetConfigRequest) Descriptor() ([]byte, []int) {
	return file_config_proto_rawDescGZIP(), []int{5}
}

func (x *GetConfigRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *GetConfigRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type SetConfigRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantId      string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	Key           string                 `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	Value         string                 `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
	Format        string                 `protobuf:"bytes,4,opt,name=format,proto3" json:"format,omitempty"`
	Description   string                 `protobuf:"bytes,5,opt,name=description,proto3" json:"description,omitempty"`
	UpdatedBy     string                 `protobuf:"bytes,6,opt,name=updated_by,json=updatedBy,proto3" json:"updated_by,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetConfigRequest) Reset() {
	*x = SetConfigRequest{}
	mi := &file_config_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetConfigRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetConfigRequest) ProtoMessage() {}

func (x *SetConfigRequest) ProtoReflect() protoreflect.Message {
	mi := &file_config_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetConfigRequest.ProtoReflect.Descriptor instead.
func (*SetConfigRequest) Descriptor() ([]byte, []int) {
	return file_config_proto_rawDescGZIP(), []int{6}
}

func (x *SetConfigRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *SetConfigRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *SetConfigRequest) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *SetConfigRequest) GetFormat() string {
	if x != nil {
		return x.Format
	}
	return ""
}

func (x *SetConfigRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *SetConfigRequest) GetUpdatedBy() string {
	if x != nil {
		return x.UpdatedBy
	}
	return ""
}

type DeleteConfigRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantId      string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	Key           string                 `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteConfigRequest) Reset() {
	*x = DeleteConfigRequest{}
	mi := &file_config_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteConfigRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteConfigRequest) ProtoMessage() {}

func (x *DeleteConfigRequest) ProtoReflect() protoreflect.Message {
	mi := &file_config_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteConfigRequest.ProtoReflect.Descriptor instead.
func (*DeleteConfigRequest) Descriptor() ([]byte, []int) {
	return file_config_proto_rawDescGZIP(), []int{7}
}

func (x *DeleteConfigRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *DeleteConfigRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type ListConfigsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantId      string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListConfigsRequest) Reset() {
	*x = ListConfigsRequest{}
	mi := &file_config_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListConfigsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListConfigsRequest) ProtoMessage() {}

func (x *ListConfigsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_config_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListConfigsRequest.ProtoReflect.Descriptor instead.
func (*ListConfigsRequest) Descriptor() ([]byte, []int) {
	return file_config_proto_rawDescGZIP(), []int{8}
}

func (x *ListConfigsRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

type ListConfigsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Configs       []*ConfigItem          `protobuf:"bytes,1,rep,name=configs,proto3" json:"configs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListConfigsResponse) Reset() {
	*x = ListConfigsResponse{}
	mi := &file_config_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListConfigsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListConfigsResponse) ProtoMessage() {}

func (x *ListConfigsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_config_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListConfigsResponse.ProtoReflect.Descriptor instead.
func (*ListConfigsResponse) Descriptor() ([]byte, []int) {
	return file_config_proto_rawDescGZIP(), []int{9}
}

func (x *ListConfigsResponse) GetConfigs() []*ConfigItem {
	if x != nil {
		return x.Configs
	}
	return nil
}

type GetConfigHistoryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantId      string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	Key           string                 `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetConfigHistoryRequest) Reset() {
	*x = GetConfigHistoryRequest{}
	mi := &file_config_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetConfigHistoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetConfigHistoryRequest) ProtoMessage() {}

func (x *GetConfigHistoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_config_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetConfigHistoryRequest.ProtoReflect.Descriptor instead.
func (*GetConfigHistoryRequest) Descriptor() ([]byte, []int) {
	return file_config_proto_rawDescGZIP(), []int{10}
}

func (x *GetConfigHistoryRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *GetConfigHistoryRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type GetConfigHistoryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	History       []*ConfigItem          `protobuf:"bytes,1,rep,name=history,proto3" json:"history,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetConfigHistoryResponse) Reset() {
	*x = GetConfigHistoryResponse{}
	mi := &file_config_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetConfigHistoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetConfigHistoryResponse) ProtoMessage() {}

func (x *GetConfigHistoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_config_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetConfigHistoryResponse.ProtoReflect.Descriptor instead.
func (*GetConfigHistoryResponse) Descriptor() ([]byte, []int) {
	return file_config_proto_rawDescGZIP(), []int{11}
}

func (x *GetConfigHistoryResponse) GetHistory() []*ConfigItem {
	if x != nil {
		return x.History
	}
	return nil
}

type RollbackConfigRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantId      string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	Key           string                 `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	Version       int32                  `protobuf:"varint,3,opt,name=version,proto3" json:"version,omitempty"`
	UpdatedBy     string                 `protobuf:"bytes,4,opt,name=updated_by,json=updatedBy,proto3" json:"updated_by,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RollbackConfigRequest) Reset() {
	*x = RollbackConfigRequest{}
	mi := &file_config_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RollbackConfigRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RollbackConfigRequest) ProtoMessage() {}

func (x *RollbackConfigRequest) ProtoReflect() protoreflect.Message {
	mi := &file_config_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RollbackConfigRequest.ProtoReflect.Descriptor instead.
func (*RollbackConfigRequest) Descriptor() ([]byte, []int) {
	return file_config_proto_rawDescGZIP(), []int{12}
}

func (x *RollbackConfigRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *RollbackConfigRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *RollbackConfigRequest) GetVersion() int32 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *RollbackConfigRequest) GetUpdatedBy() string {
	if x != nil {
		return x.UpdatedBy
	}
	return ""
}

type CreateSecretRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantId      string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	Key           string                 `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	Value         string                 `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
	KeyType       string                 `protobuf:"bytes,4,opt,name=key_type,json=keyType,proto3" json:"key_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateSecretRequest) Reset() {
	*x = CreateSecretRequest{}
	mi := &file_config_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSecretRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSecretRequest) ProtoMessage() {}

func (x *CreateSecretRequest) ProtoReflect() protoreflect.Message {
	mi := &file_config_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSecretRequest.ProtoReflect.Descriptor instead.
func (*CreateSecretRequest) Descriptor() ([]byte, []int) {
	return file_config_proto_rawDescGZIP(), []int{13}
}

func (x *CreateSecretRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *CreateSecretRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *CreateSecretRequest) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *CreateSecretRequest) GetKeyType() string {
	if x != nil {
		return x.KeyType
	}
	return ""
}

type GetSecretRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantId      string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	Key           string                 `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSecretRequest) Reset() {
	*x = GetSecretRequest{}
	mi := &file_config_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSecretRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSecretRequest) ProtoMessage() {}

func (x *GetSecretRequest) ProtoReflect() protoreflect.Message {
	mi := &file_config_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSecretRequest.ProtoReflect.Descriptor instead.
func (*GetSecretRequest) Descriptor() ([]byte, []int) {
	return file_config_proto_rawDescGZIP(), []int{14}
}

func (x *GetSecretRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *GetSecretRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type UpdateSecretRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantId      string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	Key           string                 `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	Value         string                 `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
	KeyType       string                 `protobuf:"bytes,4,opt,name=key_type,json=keyType,proto3" json:"key_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateSecretRequest) Reset() {
	*x = UpdateSecretRequest{}
	mi := &file_config_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateSecretRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateSecretRequest) ProtoMessage() {}

func (x *UpdateSecretRequest) ProtoReflect() protoreflect.Message {
	mi := &file_config_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateSecretRequest.ProtoReflect.Descriptor instead.
func (*UpdateSecretRequest) Descriptor() ([]byte, []int) {
	return file_config_proto_rawDescGZIP(), []int{15}
}

func (x *UpdateSecretRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *UpdateSecretRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *UpdateSecretRequest) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *UpdateSecretRequest) GetKeyType() string {
	if x != nil {
		return x.KeyType
	}
	return ""
}

type DeleteSecretRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantId      string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	Key           string                 `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteSecretRequest) Reset() {
	*x = DeleteSecretRequest{}
	mi := &file_config_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteSecretRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteSecretRequest) ProtoMessage() {}

func (x *DeleteSecretRequest) ProtoReflect() protoreflect.Message {
	mi := &file_config_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteSecretRequest.ProtoReflect.Descriptor instead.
func (*DeleteSecretRequest) Descriptor() ([]byte, []int) {
	return file_config_proto_rawDescGZIP(), []int{16}
}

func (x *DeleteSecretRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *DeleteSecretRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type ListSecretsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantId      string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSecretsRequest) Reset() {
	*x = ListSecretsRequest{}
	mi := &file_config_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSecretsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSecretsRequest) ProtoMessage() {}

func (x *ListSecretsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_config_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSecretsRequest.ProtoReflect.Descriptor instead.
func (*ListSecretsRequest) Descriptor() ([]byte, []int) {
	return file_config_proto_rawDescGZIP(), []int{17}
}

func (x *ListSecretsRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

type ListSecretsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Secrets       []*SecretMeta          `protobuf:"bytes,1,rep,name=secrets,proto3" json:"secrets,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSecretsResponse) Reset() {
	*x = ListSecretsResponse{}
	mi := &file_config_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSecretsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSecretsResponse) ProtoMessage() {}

func (x *ListSecretsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_config_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSecretsResponse.ProtoReflect.Descriptor instead.
func (*ListSecretsResponse) Descriptor() ([]byte, []int) {
	return file_config_proto_rawDescGZIP(), []int{18}
}

func (x *ListSecretsResponse) GetSecrets() []*SecretMeta {
	if x != nil {
		return x.Secrets
	}
	return nil
}

type RotateSecretRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantId      string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	Key           string                 `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	NewValue      string                 `protobuf:"bytes,3,opt,name=new_value,json=newValue,proto3" json:"new_value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RotateSecretRequest) Reset() {
	*x = RotateSecretRequest{}
	mi := &file_config_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RotateSecretRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RotateSecretRequest) ProtoMessage() {}

func (x *RotateSecretRequest) ProtoReflect() protoreflect.Message {
	mi := &file_config_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RotateSecretRequest.ProtoReflect.Descriptor instead.
func (*RotateSecretRequest) Descriptor() ([]byte, []int) {
	return file_config_proto_rawDescGZIP(), []int{19}
}

func (x *RotateSecretRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *RotateSecretRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *RotateSecretRequest) GetNewValue() string {
	if x != nil {
		return x.NewValue
	}
	return ""
}

type CreateChannelRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantId      string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Type          string                 `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	Config        string                 `protobuf:"bytes,4,opt,name=config,proto3" json:"config,omitempty"`
	Enabled       bool                   `protobuf:"varint,5,opt,name=enabled,proto3" json:"enabled,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateChannelRequest) Reset() {
	*x = CreateChannelRequest{}
	mi := &file_config_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateChannelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateChannelRequest) ProtoMessage() {}

func (x *CreateChannelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_config_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateChannelRequest.ProtoReflect.Descriptor instead.
func (*CreateChannelRequest) Descriptor() ([]byte, []int) {
	return file_config_proto_rawDescGZIP(), []int{20}
}

func (x *CreateChannelRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *CreateChannelRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateChannelRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *CreateChannelRequest) GetConfig() string {
	if x != nil {
		return x.Config
	}
	return ""
}

func (x *CreateChannelRequest) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

type GetChannelRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetChannelRequest) Reset() {
	*x = GetChannelRequest{}
	mi := &file_config_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetChannelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetChannelRequest) ProtoMessage() {}

func (x *GetChannelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_config_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetChannelRequest.ProtoReflect.Descriptor instead.
func (*GetChannelRequest) Descriptor() ([]byte, []int) {
	return file_config_proto_rawDescGZIP(), []int{21}
}

func (x *GetChannelRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type UpdateChannelRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Type          string                 `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	Config        string                 `protobuf:"bytes,4,opt,name=config,proto3" json:"config,omitempty"`
	Enabled       bool                   `protobuf:"varint,5,opt,name=enabled,proto3" json:"enabled,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateChannelRequest) Reset() {
	*x = UpdateChannelRequest{}
	mi := &file_config_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateChannelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateChannelRequest) ProtoMessage() {}

func (x *UpdateChannelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_config_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateChannelRequest.ProtoReflect.Descriptor instead.
func (*UpdateChannelRequest) Descriptor() ([]byte, []int) {
	return file_config_proto_rawDescGZIP(), []int{22}
}

func (x *UpdateChannelRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateChannelRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateChannelRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *UpdateChannelRequest) GetConfig() string {
	if x != nil {
		return x.Config
	}
	return ""
}

func (x *UpdateChannelRequest) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

type DeleteChannelRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	TenantId      string                 `protobuf:"bytes,2,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteChannelRequest) Reset() {
	*x = DeleteChannelRequest{}
	mi := &file_config_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteChannelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteChannelRequest) ProtoMessage() {}

func (x *DeleteChannelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_config_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteChannelRequest.ProtoReflect.Descriptor instead.
func (*DeleteChannelRequest) Descriptor() ([]byte, []int) {
	return file_config_proto_rawDescGZIP(), []int{23}
}

func (x *DeleteChannelRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *DeleteChannelRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

type ListChannelsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantId      string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListChannelsRequest) Reset() {
	*x = ListChannelsRequest{}
	mi := &file_config_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListChannelsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListChannelsRequest) ProtoMessage() {}

func (x *ListChannelsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_config_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListChannelsRequest.ProtoReflect.Descriptor instead.
func (*ListChannelsRequest) Descriptor() ([]byte, []int) {
	return file_config_proto_rawDescGZIP(), []int{24}
}

func (x *ListChannelsRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

type ListChannelsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Channels      []*NotifyChannel       `protobuf:"bytes,1,rep,name=channels,proto3" json:"channels,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListChannelsResponse) Reset() {
	*x = ListChannelsResponse{}
	mi := &file_config_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListChannelsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListChannelsResponse) ProtoMessage() {}

func (x *ListChannelsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_config_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListChannelsResponse.ProtoReflect.Descriptor instead.
func (*ListChannelsResponse) Descriptor() ([]byte, []int) {
	return file_config_proto_rawDescGZIP(), []int{25}
}

func (x *ListChannelsResponse) GetChannels() []*NotifyChannel {
	if x != nil {
		return x.Channels
	}
	return nil
}

type TestChannelRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TestChannelRequest) Reset() {
	*x = TestChannelRequest{}
	mi := &file_config_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TestChannelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TestChannelRequest) ProtoMessage() {}

func (x *TestChannelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_config_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TestChannelRequest.ProtoReflect.Descriptor instead.
func (*TestChannelRequest) Descriptor() ([]byte, []int) {
	return file_config_proto_rawDescGZIP(), []int{26}
}

func (x *TestChannelRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type TestChannelResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TestChannelResponse) Reset() {
	*x = TestChannelResponse{}
	mi := &file_config_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TestChannelResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TestChannelResponse) ProtoMessage() {}

func (x *TestChannelResponse) ProtoReflect() protoreflect.Message {
	mi := &file_config_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TestChannelResponse.ProtoReflect.Descriptor instead.
func (*TestChannelResponse) Descriptor() ([]byte, []int) {
	return file_config_proto_rawDescGZIP(), []int{27}
}

func (x *TestChannelResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *TestChannelResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type CreateTemplateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantId      string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Content       string                 `protobuf:"bytes,4,opt,name=content,proto3" json:"content,omitempty"`
	Variables     map[string]string      `protobuf:"bytes,5,rep,name=variables,proto3" json:"variables,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateTemplateRequest) Reset() {
	*x = CreateTemplateRequest{}
	mi := &file_config_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTemplateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTemplateRequest) ProtoMessage() {}

func (x *CreateTemplateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_config_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTemplateRequest.ProtoReflect.Descriptor instead.
func (*CreateTemplateRequest) Descriptor() ([]byte, []int) {
	return file_config_proto_rawDescGZIP(), []int{28}
}

func (x *CreateTemplateRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *CreateTemplateRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateTemplateRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreateTemplateRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *CreateTemplateRequest) GetVariables() map[string]string {
	if x != nil {
		return x.Variables
	}
	return nil
}

type GetTemplateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTemplateRequest) Reset() {
	*x = GetTemplateRequest{}
	mi := &file_config_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTemplateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTemplateRequest) ProtoMessage() {}

func (x *GetTemplateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_config_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTemplateRequest.ProtoReflect.Descriptor instead.
func (*GetTemplateRequest) Descriptor() ([]byte, []int) {
	return file_config_proto_rawDescGZIP(), []int{29}
}

func (x *GetTemplateRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type UpdateTemplateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Content       string                 `protobuf:"bytes,4,opt,name=content,proto3" json:"content,omitempty"`
	Variables     map[string]string      `protobuf:"bytes,5,rep,name=variables,proto3" json:"variables,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateTemplateRequest) Reset() {
	*x = UpdateTemplateRequest{}
	mi := &file_config_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateTemplateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateTemplateRequest) ProtoMessage() {}

func (x *UpdateTemplateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_config_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateTemplateRequest.ProtoReflect.Descriptor instead.
func (*UpdateTemplateRequest) Descriptor() ([]byte, []int) {
	return file_config_proto_rawDescGZIP(), []int{30}
}

func (x *UpdateTemplateRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateTemplateRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateTemplateRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *UpdateTemplateRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *UpdateTemplateRequest) GetVariables() map[string]string {
	if x != nil {
		return x.Variables
	}
	return nil
}

type DeleteTemplateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	TenantId      string                 `protobuf:"bytes,2,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteTemplateRequest) Reset() {
	*x = DeleteTemplateRequest{}
	mi := &file_config_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteTemplateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteTemplateRequest) ProtoMessage() {}

func (x *DeleteTemplateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_config_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteTemplateRequest.ProtoReflect.Descriptor instead.
func (*DeleteTemplateRequest) Descriptor() ([]byte, []int) {
	return file_config_proto_rawDescGZIP(), []int{31}
}

func (x *DeleteTemplateRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *DeleteTemplateRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

type ListTemplatesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantId      string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTemplatesRequest) Reset() {
	*x = ListTemplatesRequest{}
	mi := &file_config_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTemplatesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTemplatesRequest) ProtoMessage() {}

func (x *ListTemplatesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_config_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTemplatesRequest.ProtoReflect.Descriptor instead.
func (*ListTemplatesRequest) Descriptor() ([]byte, []int) {
	return file_config_proto_rawDescGZIP(), []int{32}
}

func (x *ListTemplatesRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

type ListTemplatesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Templates     []*ConfigTemplate      `protobuf:"bytes,1,rep,name=templates,proto3" json:"templates,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTemplatesResponse) Reset() {
	*x = ListTemplatesResponse{}
	mi := &file_config_proto_msgTypes[33]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTemplatesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTemplatesResponse) ProtoMessage() {}

func (x *ListTemplatesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_config_proto_msgTypes[33]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTemplatesResponse.ProtoReflect.Descriptor instead.
func (*ListTemplatesResponse) Descriptor() ([]byte, []int) {
	return file_config_proto_rawDescGZIP(), []int{33}
}

func (x *ListTemplatesResponse) GetTemplates() []*ConfigTemplate {
	if x != nil {
		return x.Templates
	}
	return nil
}

type ApplyTemplateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Variables     map[string]string      `protobuf:"bytes,2,rep,name=variables,proto3" json:"variables,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApplyTemplateRequest) Reset() {
	*x = ApplyTemplateRequest{}
	mi := &file_config_proto_msgTypes[34]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApplyTemplateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApplyTemplateRequest) ProtoMessage() {}

func (x *ApplyTemplateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_config_proto_msgTypes[34]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApplyTemplateRequest.ProtoReflect.Descriptor instead.
func (*ApplyTemplateRequest) Descriptor() ([]byte, []int) {
	return file_config_proto_rawDescGZIP(), []int{34}
}

func (x *ApplyTemplateRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ApplyTemplateRequest) GetVariables() map[string]string {
	if x != nil {
		return x.Variables
	}
	return nil
}

type ApplyTemplateResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	RenderedContent string                 `protobuf:"bytes,1,opt,name=rendered_content,json=renderedContent,proto3" json:"rendered_content,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ApplyTemplateResponse) Reset() {
	*x = ApplyTemplateResponse{}
	mi := &file_config_proto_msgTypes[35]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApplyTemplateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApplyTemplateResponse) ProtoMessage() {}

func (x *ApplyTemplateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_config_proto_msgTypes[35]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApplyTemplateResponse.ProtoReflect.Descriptor instead.
func (*ApplyTemplateResponse) Descriptor() ([]byte, []int) {
	return file_config_proto_rawDescGZIP(), []int{35}
}

func (x *ApplyTemplateResponse) GetRenderedContent() string {
	if x != nil {
		return x.RenderedContent
	}
	return ""
}

var File_config_proto protoreflect.FileDescriptor

const file_config_proto_rawDesc = "" +
	"\n" +
	"\fconfig.proto\x12\x11opsmesh.config.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1bgoogle/protobuf/empty.proto\"\xca\x02\n" +
	"\n" +
	"ConfigItem\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1b\n" +
	"\ttenant_id\x18\x02 \x01(\tR\btenantId\x12\x10\n" +
	"\x03key\x18\x03 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x04 \x01(\tR\x05value\x12\x16\n" +
	"\x06format\x18\x05 \x01(\tR\x06format\x12\x18\n" +
	"\aversion\x18\x06 \x01(\x05R\aversion\x12 \n" +
	"\vdescription\x18\a \x01(\tR\vdescription\x12\x1d\n" +
	"\n" +
	"updated_by\x18\b \x01(\tR\tupdatedBy\x129\n" +
	"\n" +
	"created_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"\x8c\x02\n" +
	"\n" +
	"SecretItem\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1b\n" +
	"\ttenant_id\x18\x02 \x01(\tR\btenantId\x12\x10\n" +
	"\x03key\x18\x03 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x04 \x01(\tR\x05value\x12\x19\n" +
	"\bkey_type\x18\x05 \x01(\tR\akeyType\x12\x18\n" +
	"\aversion\x18\x06 \x01(\x05R\aversion\x129\n" +
	"\n" +
	"created_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"\xf6\x01\n" +
	"\n" +
	"SecretMeta\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1b\n" +
	"\ttenant_id\x18\x02 \x01(\tR\btenantId\x12\x10\n" +
	"\x03key\x18\x03 \x01(\tR\x03key\x12\x19\n" +
	"\bkey_type\x18\x04 \x01(\tR\akeyType\x12\x18\n" +
	"\aversion\x18\x05 \x01(\x05R\aversion\x129\n" +
	"\n" +
	"created_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"\x8c\x02\n" +
	"\rNotifyChannel\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1b\n" +
	"\ttenant_id\x18\x02 \x01(\tR\btenantId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x12\n" +
	"\x04type\x18\x04 \x01(\tR\x04type\x12\x16\n" +
	"\x06config\x18\x05 \x01(\tR\x06config\x12\x18\n" +
	"\aenabled\x18\x06 \x01(\bR\aenabled\x129\n" +
	"\n" +
	"created_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"\x91\x03\n" +
	"\x0eConfigTemplate\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1b\n" +
	"\ttenant_id\x18\x02 \x01(\tR\btenantId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12\x18\n" +
	"\acontent\x18\x05 \x01(\tR\acontent\x12N\n" +
	"\tvariables\x18\x06 \x03(\v20.opsmesh.config.v1.ConfigTemplate.VariablesEntryR\tvariables\x129\n" +
	"\n" +
	"created_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x1a<\n" +
	"\x0eVariablesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"A\n" +
	"\x10GetConfigRequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12\x10\n" +
	"\x03key\x18\x02 \x01(\tR\x03key\"\xb0\x01\n" +
	"\x10SetConfigRequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12\x10\n" +
	"\x03key\x18\x02 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x03 \x01(\tR\x05value\x12\x16\n" +
	"\x06format\x18\x04 \x01(\tR\x06format\x12 \n" +
	"\vdescription\x18\x05 \x01(\tR\vdescription\x12\x1d\n" +
	"\n" +
	"updated_by\x18\x06 \x01(\tR\tupdatedBy\"D\n" +
	"\x13DeleteConfigRequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12\x10\n" +
	"\x03key\x18\x02 \x01(\tR\x03key\"1\n" +
	"\x12ListConfigsRequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\"N\n" +
	"\x13ListConfigsResponse\x127\n" +
	"\aconfigs\x18\x01 \x03(\v2\x1d.opsmesh.config.v1.ConfigItemR\aconfigs\"H\n" +
	"\x17GetConfigHistoryRequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12\x10\n" +
	"\x03key\x18\x02 \x01(\tR\x03key\"S\n" +
	"\x18GetConfigHistoryResponse\x127\n" +
	"\ahistory\x18\x01 \x03(\v2\x1d.opsmesh.config.v1.ConfigItemR\ahistory\"\x7f\n" +
	"\x15RollbackConfigRequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12\x10\n" +
	"\x03key\x18\x02 \x01(\tR\x03key\x12\x18\n" +
	"\aversion\x18\x03 \x01(\x05R\aversion\x12\x1d\n" +
	"\n" +
	"updated_by\x18\x04 \x01(\tR\tupdatedBy\"u\n" +
	"\x13CreateSecretRequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12\x10\n" +
	"\x03key\x18\x02 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x03 \x01(\tR\x05value\x12\x19\n" +
	"\bkey_type\x18\x04 \x01(\tR\akeyType\"A\n" +
	"\x10GetSecretRequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12\x10\n" +
	"\x03key\x18\x02 \x01(\tR\x03key\"u\n" +
	"\x13UpdateSecretRequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12\x10\n" +
	"\x03key\x18\x02 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x03 \x01(\tR\x05value\x12\x19\n" +
	"\bkey_type\x18\x04 \x01(\tR\akeyType\"D\n" +
	"\x13DeleteSecretRequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12\x10\n" +
	"\x03key\x18\x02 \x01(\tR\x03key\"1\n" +
	"\x12ListSecretsRequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\"N\n" +
	"\x13ListSecretsResponse\x127\n" +
	"\asecrets\x18\x01 \x03(\v2\x1d.opsmesh.config.v1.SecretMetaR\asecrets\"a\n" +
	"\x13RotateSecretRequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12\x10\n" +
	"\x03key\x18\x02 \x01(\tR\x03key\x12\x1b\n" +
	"\tnew_value\x18\x03 \x01(\tR\bnewValue\"\x8d\x01\n" +
	"\x14CreateChannelRequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04type\x18\x03 \x01(\tR\x04type\x12\x16\n" +
	"\x06config\x18\x04 \x01(\tR\x06config\x12\x18\n" +
	"\aenabled\x18\x05 \x01(\bR\aenabled\"#\n" +
	"\x11GetChannelRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\x80\x01\n" +
	"\x14UpdateChannelRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04type\x18\x03 \x01(\tR\x04type\x12\x16\n" +
	"\x06config\x18\x04 \x01(\tR\x06config\x12\x18\n" +
	"\aenabled\x18\x05 \x01(\bR\aenabled\"C\n" +
	"\x14DeleteChannelRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1b\n" +
	"\ttenant_id\x18\x02 \x01(\tR\btenantId\"2\n" +
	"\x13ListChannelsRequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\"T\n" +
	"\x14ListChannelsResponse\x12<\n" +
	"\bchannels\x18\x01 \x03(\v2 .opsmesh.config.v1.NotifyChannelR\bchannels\"$\n" +
	"\x12TestChannelRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"I\n" +
	"\x13TestChannelResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\x99\x02\n" +
	"\x15CreateTemplateRequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x18\n" +
	"\acontent\x18\x04 \x01(\tR\acontent\x12U\n" +
	"\tvariables\x18\x05 \x03(\v27.opsmesh.config.v1.CreateTemplateRequest.VariablesEntryR\tvariables\x1a<\n" +
	"\x0eVariablesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"$\n" +
	"\x12GetTemplateRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\x8c\x02\n" +
	"\x15UpdateTemplateRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x18\n" +
	"\acontent\x18\x04 \x01(\tR\acontent\x12U\n" +
	"\tvariables\x18\x05 \x03(\v27.opsmesh.config.v1.UpdateTemplateRequest.VariablesEntryR\tvariables\x1a<\n" +
	"\x0eVariablesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"D\n" +
	"\x15DeleteTemplateRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1b\n" +
	"\ttenant_id\x18\x02 \x01(\tR\btenantId\"3\n" +
	"\x14ListTemplatesRequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\"X\n" +
	"\x15ListTemplatesResponse\x12?\n" +
	"\ttemplates\x18\x01 \x03(\v2!.opsmesh.config.v1.ConfigTemplateR\ttemplates\"\xba\x01\n" +
	"\x14ApplyTemplateRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12T\n" +
	"\tvariables\x18\x02 \x03(\v26.opsmesh.config.v1.ApplyTemplateRequest.VariablesEntryR\tvariables\x1a<\n" +
	"\x0eVariablesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"B\n" +
	"\x15ApplyTemplateResponse\x12)\n" +
	"\x10rendered_content\x18\x01 \x01(\tR\x0frenderedContent2\xa7\x04\n" +
	"\rConfigService\x12O\n" +
	"\tGetConfig\x12#.opsmesh.config.v1.GetConfigRequest\x1a\x1d.opsmesh.config.v1.ConfigItem\x12O\n" +
	"\tSetConfig\x12#.opsmesh.config.v1.SetConfigRequest\x1a\x1d.opsmesh.config.v1.ConfigItem\x12N\n" +
	"\fDeleteConfig\x12&.opsmesh.config.v1.DeleteConfigRequest\x1a\x16.google.protobuf.Empty\x12\\\n" +
	"\vListConfigs\x12%.opsmesh.config.v1.ListConfigsRequest\x1a&.opsmesh.config.v1.ListConfigsResponse\x12k\n" +
	"\x10GetConfigHistory\x12*.opsmesh.config.v1.GetConfigHistoryRequest\x1a+.opsmesh.config.v1.GetConfigHistoryResponse\x12Y\n" +
	"\x0eRollbackConfig\x12(.opsmesh.config.v1.RollbackConfigRequest\x1a\x1d.opsmesh.config.v1.ConfigItem2\x93\x04\n" +
	"\rSecretService\x12U\n" +
	"\fCreateSecret\x12&.opsmesh.config.v1.CreateSecretRequest\x1a\x1d.opsmesh.config.v1.SecretMeta\x12O\n" +
	"\tGetSecret\x12#.opsmesh.config.v1.GetSecretRequest\x1a\x1d.opsmesh.config.v1.SecretItem\x12U\n" +
	"\fUpdateSecret\x12&.opsmesh.config.v1.UpdateSecretRequest\x1a\x1d.opsmesh.config.v1.SecretMeta\x12N\n" +
	"\fDeleteSecret\x12&.opsmesh.config.v1.DeleteSecretRequest\x1a\x16.google.protobuf.Empty\x12\\\n" +
	"\vListSecrets\x12%.opsmesh.config.v1.ListSecretsRequest\x1a&.opsmesh.config.v1.ListSecretsResponse\x12U\n" +
	"\fRotateSecret\x12&.opsmesh.config.v1.RotateSecretRequest\x1a\x1d.opsmesh.config.v1.SecretMeta2\xb5\x04\n" +
	"\x14NotifyChannelService\x12Z\n" +
	"\rCreateChannel\x12'.opsmesh.config.v1.CreateChannelRequest\x1a .opsmesh.config.v1.NotifyChannel\x12T\n" +
	"\n" +
	"GetChannel\x12$.opsmesh.config.v1.GetChannelRequest\x1a .opsmesh.config.v1.NotifyChannel\x12Z\n" +
	"\rUpdateChannel\x12'.opsmesh.config.v1.UpdateChannelRequest\x1a .opsmesh.config.v1.NotifyChannel\x12P\n" +
	"\rDeleteChannel\x12'.opsmesh.config.v1.DeleteChannelRequest\x1a\x16.google.protobuf.Empty\x12_\n" +
	"\fListChannels\x12&.opsmesh.config.v1.ListChannelsRequest\x1a'.opsmesh.config.v1.ListChannelsResponse\x12\\\n" +
	"\vTestChannel\x12%.opsmesh.config.v1.TestChannelRequest\x1a&.opsmesh.config.v1.TestChannelResponse2\xc4\x04\n" +
	"\x0fTemplateService\x12]\n" +
	"\x0eCreateTemplate\x12(.opsmesh.config.v1.CreateTemplateRequest\x1a!.opsmesh.config.v1.ConfigTemplate\x12W\n" +
	"\vGetTemplate\x12%.opsmesh.config.v1.GetTemplateRequest\x1a!.opsmesh.config.v1.ConfigTemplate\x12]\n" +
	"\x0eUpdateTemplate\x12(.opsmesh.config.v1.UpdateTemplateRequest\x1a!.opsmesh.config.v1.ConfigTemplate\x12R\n" +
	"\x0eDeleteTemplate\x12(.opsmesh.config.v1.DeleteTemplateRequest\x1a\x16.google.protobuf.Empty\x12b\n" +
	"\rListTemplates\x12'.opsmesh.config.v1.ListTemplatesRequest\x1a(.opsmesh.config.v1.ListTemplatesResponse\x12b\n" +
	"\rApplyTemplate\x12'.opsmesh.config.v1.ApplyTemplateRequest\x1a(.opsmesh.config.v1.ApplyTemplateResponseBGZEgithub.com/Levango7/OpsMesh/services/config-svc/api/proto/v1;configv1b\x06proto3"

var (
	file_config_proto_rawDescOnce sync.Once
	file_config_proto_rawDescData []byte
)

func file_config_proto_rawDescGZIP() []byte {
	file_config_proto_rawDescOnce.Do(func() {
		file_config_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_config_proto_rawDesc), len(file_config_proto_rawDesc)))
	})
	return file_config_proto_rawDescData
}

var file_config_proto_msgTypes = make([]protoimpl.MessageInfo, 40)
var file_config_proto_goTypes = []any{
	(*ConfigItem)(nil),               // 0: opsmesh.config.v1.ConfigItem
	(*SecretItem)(nil),               // 1: opsmesh.config.v1.SecretItem
	(*SecretMeta)(nil),               // 2: opsmesh.config.v1.SecretMeta
	(*NotifyChannel)(nil),            // 3: opsmesh.config.v1.NotifyChannel
	(*ConfigTemplate)(nil),           // 4: opsmesh.config.v1.ConfigTemplate
	(*GetConfigRequest)(nil),         // 5: opsmesh.config.v1.GetConfigRequest
	(*SetConfigRequest)(nil),         // 6: opsmesh.config.v1.SetConfigRequest
	(*DeleteConfigRequest)(nil),      // 7: opsmesh.config.v1.DeleteConfigRequest
	(*ListConfigsRequest)(nil),       // 8: opsmesh.config.v1.ListConfigsRequest
	(*ListConfigsResponse)(nil),      // 9: opsmesh.config.v1.ListConfigsResponse
	(*GetConfigHistoryRequest)(nil),  // 10: opsmesh.config.v1.GetConfigHistoryRequest
	(*GetConfigHistoryResponse)(nil), // 11: opsmesh.config.v1.GetConfigHistoryResponse
	(*RollbackConfigRequest)(nil),    // 12: opsmesh.config.v1.RollbackConfigRequest
	(*CreateSecretRequest)(nil),      // 13: opsmesh.config.v1.CreateSecretRequest
	(*GetSecretRequest)(nil),         // 14: opsmesh.config.v1.GetSecretRequest
	(*UpdateSecretRequest)(nil),      // 15: opsmesh.config.v1.UpdateSecretRequest
	(*DeleteSecretRequest)(nil),      // 16: opsmesh.config.v1.DeleteSecretRequest
	(*ListSecretsRequest)(nil),       // 17: opsmesh.config.v1.ListSecretsRequest
	(*ListSecretsResponse)(nil),      // 18: opsmesh.config.v1.ListSecretsResponse
	(*RotateSecretRequest)(nil),      // 19: opsmesh.config.v1.RotateSecretRequest
	(*CreateChannelRequest)(nil),     // 20: opsmesh.config.v1.CreateChannelRequest
	(*GetChannelRequest)(nil),        // 21: opsmesh.config.v1.GetChannelRequest
	(*UpdateChannelRequest)(nil),     // 22: opsmesh.config.v1.UpdateChannelRequest
	(*DeleteChannelRequest)(nil),     // 23: opsmesh.config.v1.DeleteChannelRequest
	(*ListChannelsRequest)(nil),      // 24: opsmesh.config.v1.ListChannelsRequest
	(*ListChannelsResponse)(nil),     // 25: opsmesh.config.v1.ListChannelsResponse
	(*TestChannelRequest)(nil),       // 26: opsmesh.config.v1.TestChannelRequest
	(*TestChannelResponse)(nil),      // 27: opsmesh.config.v1.TestChannelResponse
	(*CreateTemplateRequest)(nil),    // 28: opsmesh.config.v1.CreateTemplateRequest
	(*GetTemplateRequest)(nil),       // 29: opsmesh.config.v1.GetTemplateRequest
	(*UpdateTemplateRequest)(nil),    // 30: opsmesh.config.v1.UpdateTemplateRequest
	(*DeleteTemplateRequest)(nil),    // 31: opsmesh.config.v1.DeleteTemplateRequest
	(*ListTemplatesRequest)(nil),     // 32: opsmesh.config.v1.ListTemplatesRequest
	(*ListTemplatesResponse)(nil),    // 33: opsmesh.config.v1.ListTemplatesResponse
	(*ApplyTemplateRequest)(nil),     // 34: opsmesh.config.v1.ApplyTemplateRequest
	(*ApplyTemplateResponse)(nil),    // 35: opsmesh.config.v1.ApplyTemplateResponse
	nil,                              // 36: opsmesh.config.v1.ConfigTemplate.VariablesEntry
	nil,                              // 37: opsmesh.config.v1.CreateTemplateRequest.VariablesEntry
	nil,                              // 38: opsmesh.config.v1.UpdateTemplateRequest.VariablesEntry
	nil,                              // 39: opsmesh.config.v1.ApplyTemplateRequest.VariablesEntry
	(*timestamppb.Timestamp)(nil),    // 40: google.protobuf.Timestamp
	(*emptypb.Empty)(nil),            // 41: google.protobuf.Empty
}
var file_config_proto_depIdxs = []int32{
	40, // 0: opsmesh.config.v1.ConfigItem.created_at:type_name -> google.protobuf.Timestamp
	40, // 1: opsmesh.config.v1.ConfigItem.updated_at:type_name -> google.protobuf.Timestamp
	40, // 2: opsmesh.config.v1.SecretItem.created_at:type_name -> google.protobuf.Timestamp
	40, // 3: opsmesh.config.v1.SecretItem.updated_at:type_name -> google.protobuf.Timestamp
	40, // 4: opsmesh.config.v1.SecretMeta.created_at:type_name -> google.protobuf.Timestamp
	40, // 5: opsmesh.config.v1.SecretMeta.updated_at:type_name -> google.protobuf.Timestamp
	40, // 6: opsmesh.config.v1.NotifyChannel.created_at:type_name -> google.protobuf.Timestamp
	40, // 7: opsmesh.config.v1.NotifyChannel.updated_at:type_name -> google.protobuf.Timestamp
	36, // 8: opsmesh.config.v1.ConfigTemplate.variables:type_name -> opsmesh.config.v1.ConfigTemplate.VariablesEntry
	40, // 9: opsmesh.config.v1.ConfigTemplate.created_at:type_name -> google.protobuf.Timestamp
	40, // 10: opsmesh.config.v1.ConfigTemplate.updated_at:type_name -> google.protobuf.Timestamp
	0,  // 11: opsmesh.config.v1.ListConfigsResponse.configs:type_name -> opsmesh.config.v1.ConfigItem
	0,  // 12: opsmesh.config.v1.GetConfigHistoryResponse.history:type_name -> opsmesh.config.v1.ConfigItem
	2,  // 13: opsmesh.config.v1.ListSecretsResponse.secrets:type_name -> opsmesh.config.v1.SecretMeta
	3,  // 14: opsmesh.config.v1.ListChannelsResponse.channels:type_name -> opsmesh.config.v1.NotifyChannel
	37, // 15: opsmesh.config.v1.CreateTemplateRequest.variables:type_name -> opsmesh.config.v1.CreateTemplateRequest.VariablesEntry
	38, // 16: opsmesh.config.v1.UpdateTemplateRequest.variables:type_name -> opsmesh.config.v1.UpdateTemplateRequest.VariablesEntry
	4,  // 17: opsmesh.config.v1.ListTemplatesResponse.templates:type_name -> opsmesh.config.v1.ConfigTemplate
	39, // 18: opsmesh.config.v1.ApplyTemplateRequest.variables:type_name -> opsmesh.config.v1.ApplyTemplateRequest.VariablesEntry
	5,  // 19: opsmesh.config.v1.ConfigService.GetConfig:input_type -> opsmesh.config.v1.GetConfigRequest
	6,  // 20: opsmesh.config.v1.ConfigService.SetConfig:input_type -> opsmesh.config.v1.SetConfigRequest
	7,  // 21: opsmesh.config.v1.ConfigService.DeleteConfig:input_type -> opsmesh.config.v1.DeleteConfigRequest
	8,  // 22: opsmesh.config.v1.ConfigService.ListConfigs:input_type -> opsmesh.config.v1.ListConfigsRequest
	10, // 23: opsmesh.config.v1.ConfigService.GetConfigHistory:input_type -> opsmesh.config.v1.GetConfigHistoryRequest
	12, // 24: opsmesh.config.v1.ConfigService.RollbackConfig:input_type -> opsmesh.config.v1.RollbackConfigRequest
	13, // 25: opsmesh.config.v1.SecretService.CreateSecret:input_type -> opsmesh.config.v1.CreateSecretRequest
	14, // 26: opsmesh.config.v1.SecretService.GetSecret:input_type -> opsmesh.config.v1.GetSecretRequest
	15, // 27: opsmesh.config.v1.SecretService.UpdateSecret:input_type -> opsmesh.config.v1.UpdateSecretRequest
	16, // 28: opsmesh.config.v1.SecretService.DeleteSecret:input_type -> opsmesh.config.v1.DeleteSecretRequest
	17, // 29: opsmesh.config.v1.SecretService.ListSecrets:input_type -> opsmesh.config.v1.ListSecretsRequest
	19, // 30: opsmesh.config.v1.SecretService.RotateSecret:input_type -> opsmesh.config.v1.RotateSecretRequest
	20, // 31: opsmesh.config.v1.NotifyChannelService.CreateChannel:input_type -> opsmesh.config.v1.CreateChannelRequest
	21, // 32: opsmesh.config.v1.NotifyChannelService.GetChannel:input_type -> opsmesh.config.v1.GetChannelRequest
	22, // 33: opsmesh.config.v1.NotifyChannelService.UpdateChannel:input_type -> opsmesh.config.v1.UpdateChannelRequest
	23, // 34: opsmesh.config.v1.NotifyChannelService.DeleteChannel:input_type -> opsmesh.config.v1.DeleteChannelRequest
	24, // 35: opsmesh.config.v1.NotifyChannelService.ListChannels:input_type -> opsmesh.config.v1.ListChannelsRequest
	26, // 36: opsmesh.config.v1.NotifyChannelService.TestChannel:input_type -> opsmesh.config.v1.TestChannelRequest
	28, // 37: opsmesh.config.v1.TemplateService.CreateTemplate:input_type -> opsmesh.config.v1.CreateTemplateRequest
	29, // 38: opsmesh.config.v1.TemplateService.GetTemplate:input_type -> opsmesh.config.v1.GetTemplateRequest
	30, // 39: opsmesh.config.v1.TemplateService.UpdateTemplate:input_type -> opsmesh.config.v1.UpdateTemplateRequest
	31, // 40: opsmesh.config.v1.TemplateService.DeleteTemplate:input_type -> opsmesh.config.v1.DeleteTemplateRequest
	32, // 41: opsmesh.config.v1.TemplateService.ListTemplates:input_type -> opsmesh.config.v1.ListTemplatesRequest
	34, // 42: opsmesh.config.v1.TemplateService.ApplyTemplate:input_type -> opsmesh.config.v1.ApplyTemplateRequest
	0,  // 43: opsmesh.config.v1.ConfigService.GetConfig:output_type -> opsmesh.config.v1.ConfigItem
	0,  // 44: opsmesh.config.v1.ConfigService.SetConfig:output_type -> opsmesh.config.v1.ConfigItem
	41, // 45: opsmesh.config.v1.ConfigService.DeleteConfig:output_type -> google.protobuf.Empty
	9,  // 46: opsmesh.config.v1.ConfigService.ListConfigs:output_type -> opsmesh.config.v1.ListConfigsResponse
	11, // 47: opsmesh.config.v1.ConfigService.GetConfigHistory:output_type -> opsmesh.config.v1.GetConfigHistoryResponse
	0,  // 48: opsmesh.config.v1.ConfigService.RollbackConfig:output_type -> opsmesh.config.v1.ConfigItem
	2,  // 49: opsmesh.config.v1.SecretService.CreateSecret:output_type -> opsmesh.config.v1.SecretMeta
	1,  // 50: opsmesh.config.v1.SecretService.GetSecret:output_type -> opsmesh.config.v1.SecretItem
	2,  // 51: opsmesh.config.v1.SecretService.UpdateSecret:output_type -> opsmesh.config.v1.SecretMeta
	41, // 52: opsmesh.config.v1.SecretService.DeleteSecret:output_type -> google.protobuf.Empty
	18, // 53: opsmesh.config.v1.SecretService.ListSecrets:output_type -> opsmesh.config.v1.ListSecretsResponse
	2,  // 54: opsmesh.config.v1.SecretService.RotateSecret:output_type -> opsmesh.config.v1.SecretMeta
	3,  // 55: opsmesh.config.v1.NotifyChannelService.CreateChannel:output_type -> opsmesh.config.v1.NotifyChannel
	3,  // 56: opsmesh.config.v1.NotifyChannelService.GetChannel:output_type -> opsmesh.config.v1.NotifyChannel
	3,  // 57: opsmesh.config.v1.NotifyChannelService.UpdateChannel:output_type -> opsmesh.config.v1.NotifyChannel
	41, // 58: opsmesh.config.v1.NotifyChannelService.DeleteChannel:output_type -> google.protobuf.Empty
	25, // 59: opsmesh.config.v1.NotifyChannelService.ListChannels:output_type -> opsmesh.config.v1.ListChannelsResponse
	27, // 60: opsmesh.config.v1.NotifyChannelService.TestChannel:output_type -> opsmesh.config.v1.TestChannelResponse
	4,  // 61: opsmesh.config.v1.TemplateService.CreateTemplate:output_type -> opsmesh.config.v1.ConfigTemplate
	4,  // 62: opsmesh.config.v1.TemplateService.GetTemplate:output_type -> opsmesh.config.v1.ConfigTemplate
	4,  // 63: opsmesh.config.v1.TemplateService.UpdateTemplate:output_type -> opsmesh.config.v1.ConfigTemplate
	41, // 64: opsmesh.config.v1.TemplateService.DeleteTemplate:output_type -> google.protobuf.Empty
	33, // 65: opsmesh.config.v1.TemplateService.ListTemplates:output_type -> opsmesh.config.v1.ListTemplatesResponse
	35, // 66: opsmesh.config.v1.TemplateService.ApplyTemplate:output_type -> opsmesh.config.v1.ApplyTemplateResponse
	43, // [43:67] is the sub-list for method output_type
	19, // [19:43] is the sub-list for method input_type
	19, // [19:19] is the sub-list for extension type_name
	19, // [19:19] is the sub-list for extension extendee
	0,  // [0:19] is the sub-list for field type_name
}

func init() { file_config_proto_init() }
func file_config_proto_init() {
	if File_config_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_config_proto_rawDesc), len(file_config_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   40,
			NumExtensions: 0,
			NumServices:   4,
		},
		GoTypes:           file_config_proto_goTypes,
		DependencyIndexes: file_config_proto_depIdxs,
		MessageInfos:      file_config_proto_msgTypes,
	}.Build()
	File_config_proto = out.File
	file_config_proto_goTypes = nil
	file_config_proto_depIdxs = nil
}
