// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.36.2
// source: device.proto

package devicev1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	DeviceService_RegisterDevice_FullMethodName  = "/opsmesh.device.v1.DeviceService/RegisterDevice"
	DeviceService_Heartbeat_FullMethodName       = "/opsmesh.device.v1.DeviceService/Heartbeat"
	DeviceService_GetDevice_FullMethodName       = "/opsmesh.device.v1.DeviceService/GetDevice"
	DeviceService_ListDevices_FullMethodName     = "/opsmesh.device.v1.DeviceService/ListDevices"
	DeviceService_UpdateDevice_FullMethodName    = "/opsmesh.device.v1.DeviceService/UpdateDevice"
	DeviceService_DeleteDevice_FullMethodName    = "/opsmesh.device.v1.DeviceService/DeleteDevice"
	DeviceService_GetDeviceStatus_FullMethodName = "/opsmesh.device.v1.DeviceService/GetDeviceStatus"
)

// DeviceServiceClient is the client API for DeviceService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// DeviceService provides device registration, lifecycle, and status management.
type DeviceServiceClient interface {
	// RegisterDevice registers a new device.
	RegisterDevice(ctx context.Context, in *RegisterDeviceRequest, opts ...grpc.CallOption) (*Device, error)
	// Heartbeat updates device heartbeat timestamp.
	Heartbeat(ctx context.Context, in *HeartbeatRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// GetDevice retrieves a device by ID.
	GetDevice(ctx context.Context, in *GetDeviceRequest, opts ...grpc.CallOption) (*Device, error)
	// ListDevices lists devices with optional filtering.
	ListDevices(ctx context.Context, in *ListDevicesRequest, opts ...grpc.CallOption) (*ListDevicesResponse, error)
	// UpdateDevice updates device information.
	UpdateDevice(ctx context.Context, in *UpdateDeviceRequest, opts ...grpc.CallOption) (*Device, error)
	// DeleteDevice removes a device.
	DeleteDevice(ctx context.Context, in *DeleteDeviceRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// GetDeviceStatus returns the current status of a device.
	GetDeviceStatus(ctx context.Context, in *GetDeviceStatusRequest, opts ...grpc.CallOption) (*DeviceStatus, error)
}

type deviceServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewDeviceServiceClient(cc grpc.ClientConnInterface) DeviceServiceClient {
	return &deviceServiceClient{cc}
}

func (c *deviceServiceClient) RegisterDevice(ctx context.Context, in *RegisterDeviceRequest, opts ...grpc.CallOption) (*Device, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Device)
	err := c.cc.Invoke(ctx, DeviceService_RegisterDevice_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *deviceServiceClient) Heartbeat(ctx context.Context, in *HeartbeatRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, DeviceService_Heartbeat_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *deviceServiceClient) GetDevice(ctx context.Context, in *GetDeviceRequest, opts ...grpc.CallOption) (*Device, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Device)
	err := c.cc.Invoke(ctx, DeviceService_GetDevice_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *deviceServiceClient) ListDevices(ctx context.Context, in *ListDevicesRequest, opts ...grpc.CallOption) (*ListDevicesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListDevicesResponse)
	err := c.cc.Invoke(ctx, DeviceService_ListDevices_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *deviceServiceClient) UpdateDevice(ctx context.Context, in *UpdateDeviceRequest, opts ...grpc.CallOption) (*Device, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Device)
	err := c.cc.Invoke(ctx, DeviceService_UpdateDevice_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *deviceServiceClient) DeleteDevice(ctx context.Context, in *DeleteDeviceRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, DeviceService_DeleteDevice_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *deviceServiceClient) GetDeviceStatus(ctx context.Context, in *GetDeviceStatusRequest, opts ...grpc.CallOption) (*DeviceStatus, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeviceStatus)
	err := c.cc.Invoke(ctx, DeviceService_GetDeviceStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DeviceServiceServer is the server API for DeviceService service.
// All implementations must embed UnimplementedDeviceServiceServer
// for forward compatibility.
//
// DeviceService provides device registration, lifecycle, and status management.
type DeviceServiceServer interface {
	// RegisterDevice registers a new device.
	RegisterDevice(context.Context, *RegisterDeviceRequest) (*Device, error)
	// Heartbeat updates device heartbeat timestamp.
	Heartbeat(context.Context, *HeartbeatRequest) (*emptypb.Empty, error)
	// GetDevice retrieves a device by ID.
	GetDevice(context.Context, *GetDeviceRequest) (*Device, error)
	// ListDevices lists devices with optional filtering.
	ListDevices(context.Context, *ListDevicesRequest) (*ListDevicesResponse, error)
	// UpdateDevice updates device information.
	UpdateDevice(context.Context, *UpdateDeviceRequest) (*Device, error)
	// DeleteDevice removes a device.
	DeleteDevice(context.Context, *DeleteDeviceRequest) (*emptypb.Empty, error)
	// GetDeviceStatus returns the current status of a device.
	GetDeviceStatus(context.Context, *GetDeviceStatusRequest) (*DeviceStatus, error)
	mustEmbedUnimplementedDeviceServiceServer()
}

// UnimplementedDeviceServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDeviceServiceServer struct{}

func (UnimplementedDeviceServiceServer) RegisterDevice(context.Context, *RegisterDeviceRequest) (*Device, error) {
	return nil, status.Error(codes.Unimplemented, "method RegisterDevice not implemented")
}
func (UnimplementedDeviceServiceServer) Heartbeat(context.Context, *HeartbeatRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method Heartbeat not implemented")
}
func (UnimplementedDeviceServiceServer) GetDevice(context.Context, *GetDeviceRequest) (*Device, error) {
	return nil, status.Error(codes.Unimplemented, "method GetDevice not implemented")
}
func (UnimplementedDeviceServiceServer) ListDevices(context.Context, *ListDevicesRequest) (*ListDevicesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListDevices not implemented")
}
func (UnimplementedDeviceServiceServer) UpdateDevice(context.Context, *UpdateDeviceRequest) (*Device, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateDevice not implemented")
}
func (UnimplementedDeviceServiceServer) DeleteDevice(context.Context, *DeleteDeviceRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteDevice not implemented")
}
func (UnimplementedDeviceServiceServer) GetDeviceStatus(context.Context, *GetDeviceStatusRequest) (*DeviceStatus, error) {
	return nil, status.Error(codes.Unimplemented, "method GetDeviceStatus not implemented")
}
func (UnimplementedDeviceServiceServer) mustEmbedUnimplementedDeviceServiceServer() {}
func (UnimplementedDeviceServiceServer) testEmbeddedByValue()                       {}

// UnsafeDeviceServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DeviceServiceServer will
// result in compilation errors.
type UnsafeDeviceServiceServer interface {
	mustEmbedUnimplementedDeviceServiceServer()
}

func RegisterDeviceServiceServer(s grpc.ServiceRegistrar, srv DeviceServiceServer) {
	// If the following call panics, it indicates UnimplementedDeviceServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&DeviceService_ServiceDesc, srv)
}

func _DeviceService_RegisterDevice_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterDeviceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeviceServiceServer).RegisterDevice(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DeviceService_RegisterDevice_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeviceServiceServer).RegisterDevice(ctx, req.(*RegisterDeviceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DeviceService_Heartbeat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HeartbeatRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeviceServiceServer).Heartbeat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DeviceService_Heartbeat_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeviceServiceServer).Heartbeat(ctx, req.(*HeartbeatRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DeviceService_GetDevice_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDeviceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeviceServiceServer).GetDevice(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DeviceService_GetDevice_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeviceServiceServer).GetDevice(ctx, req.(*GetDeviceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DeviceService_ListDevices_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListDevicesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeviceServiceServer).ListDevices(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DeviceService_ListDevices_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeviceServiceServer).ListDevices(ctx, req.(*ListDevicesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DeviceService_UpdateDevice_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateDeviceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeviceServiceServer).UpdateDevice(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DeviceService_UpdateDevice_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeviceServiceServer).UpdateDevice(ctx, req.(*UpdateDeviceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DeviceService_DeleteDevice_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteDeviceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeviceServiceServer).DeleteDevice(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DeviceService_DeleteDevice_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeviceServiceServer).DeleteDevice(ctx, req.(*DeleteDeviceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DeviceService_GetDeviceStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDeviceStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeviceServiceServer).GetDeviceStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DeviceService_GetDeviceStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeviceServiceServer).GetDeviceStatus(ctx, req.(*GetDeviceStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// DeviceService_ServiceDesc is the grpc.ServiceDesc for DeviceService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DeviceService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "opsmesh.device.v1.DeviceService",
	HandlerType: (*DeviceServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RegisterDevice",
			Handler:    _DeviceService_RegisterDevice_Handler,
		},
		{
			MethodName: "Heartbeat",
			Handler:    _DeviceService_Heartbeat_Handler,
		},
		{
			MethodName: "GetDevice",
			Handler:    _DeviceService_GetDevice_Handler,
		},
		{
			MethodName: "ListDevices",
			Handler:    _DeviceService_ListDevices_Handler,
		},
		{
			MethodName: "UpdateDevice",
			Handler:    _DeviceService_UpdateDevice_Handler,
		},
		{
			MethodName: "DeleteDevice",
			Handler:    _DeviceService_DeleteDevice_Handler,
		},
		{
			MethodName: "GetDeviceStatus",
			Handler:    _DeviceService_GetDeviceStatus_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "device.proto",
}

const (
	AgentService_RegisterAgent_FullMethodName     = "/opsmesh.device.v1.AgentService/RegisterAgent"
	AgentService_GetAgent_FullMethodName          = "/opsmesh.device.v1.AgentService/GetAgent"
	AgentService_ListAgents_FullMethodName        = "/opsmesh.device.v1.AgentService/ListAgents"
	AgentService_UpdateAgentStatus_FullMethodName = "/opsmesh.device.v1.AgentService/UpdateAgentStatus"
	AgentService_AgentHeartbeat_FullMethodName    = "/opsmesh.device.v1.AgentService/AgentHeartbeat"
)

// AgentServiceClient is the client API for AgentService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// AgentService provides agent registration, heartbeat, and status tracking.
type AgentServiceClient interface {
	// RegisterAgent registers a new agent.
	RegisterAgent(ctx context.Context, in *RegisterAgentRequest, opts ...grpc.CallOption) (*Agent, error)
	// GetAgent retrieves an agent by ID.
	GetAgent(ctx context.Context, in *GetAgentRequest, opts ...grpc.CallOption) (*Agent, error)
	// ListAgents lists agents with optional filtering.
	ListAgents(ctx context.Context, in *ListAgentsRequest, opts ...grpc.CallOption) (*ListAgentsResponse, error)
	// UpdateAgentStatus updates agent status.
	UpdateAgentStatus(ctx context.Context, in *UpdateAgentStatusRequest, opts ...grpc.CallOption) (*Agent, error)
	// Heartbeat updates agent heartbeat.
	AgentHeartbeat(ctx context.Context, in *AgentHeartbeatRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
}

type agentServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAgentServiceClient(cc grpc.ClientConnInterface) AgentServiceClient {
	return &agentServiceClient{cc}
}

func (c *agentServiceClient) RegisterAgent(ctx context.Context, in *RegisterAgentRequest, opts ...grpc.CallOption) (*Agent, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Agent)
	err := c.cc.Invoke(ctx, AgentService_RegisterAgent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) GetAgent(ctx context.Context, in *GetAgentRequest, opts ...grpc.CallOption) (*Agent, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Agent)
	err := c.cc.Invoke(ctx, AgentService_GetAgent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) ListAgents(ctx context.Context, in *ListAgentsRequest, opts ...grpc.CallOption) (*ListAgentsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListAgentsResponse)
	err := c.cc.Invoke(ctx, AgentService_ListAgents_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) UpdateAgentStatus(ctx context.Context, in *UpdateAgentStatusRequest, opts ...grpc.CallOption) (*Agent, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Agent)
	err := c.cc.Invoke(ctx, AgentService_UpdateAgentStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) AgentHeartbeat(ctx context.Context, in *AgentHeartbeatRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, AgentService_AgentHeartbeat_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AgentServiceServer is the server API for AgentService service.
// All implementations must embed UnimplementedAgentServiceServer
// for forward compatibility.
//
// AgentService provides agent registration, heartbeat, and status tracking.
type AgentServiceServer interface {
	// RegisterAgent registers a new agent.
	RegisterAgent(context.Context, *RegisterAgentRequest) (*Agent, error)
	// GetAgent retrieves an agent by ID.
	GetAgent(context.Context, *GetAgentRequest) (*Agent, error)
	// ListAgents lists agents with optional filtering.
	ListAgents(context.Context, *ListAgentsRequest) (*ListAgentsResponse, error)
	// UpdateAgentStatus updates agent status.
	UpdateAgentStatus(context.Context, *UpdateAgentStatusRequest) (*Agent, error)
	// Heartbeat updates agent heartbeat.
	AgentHeartbeat(context.Context, *AgentHeartbeatRequest) (*emptypb.Empty, error)
	mustEmbedUnimplementedAgentServiceServer()
}

// UnimplementedAgentServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAgentServiceServer struct{}

func (UnimplementedAgentServiceServer) RegisterAgent(context.Context, *RegisterAgentRequest) (*Agent, error) {
	return nil, status.Error(codes.Unimplemented, "method RegisterAgent not implemented")
}
func (UnimplementedAgentServiceServer) GetAgent(context.Context, *GetAgentRequest) (*Agent, error) {
	return nil, status.Error(codes.Unimplemented, "method GetAgent not implemented")
}
func (UnimplementedAgentServiceServer) ListAgents(context.Context, *ListAgentsRequest) (*ListAgentsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListAgents not implemented")
}
func (UnimplementedAgentServiceServer) UpdateAgentStatus(context.Context, *UpdateAgentStatusRequest) (*Agent, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateAgentStatus not implemented")
}
func (UnimplementedAgentServiceServer) AgentHeartbeat(context.Context, *AgentHeartbeatRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method AgentHeartbeat not implemented")
}
func (UnimplementedAgentServiceServer) mustEmbedUnimplementedAgentServiceServer() {}
func (UnimplementedAgentServiceServer) testEmbeddedByValue()                      {}

// UnsafeAgentServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AgentServiceServer will
// result in compilation errors.
type UnsafeAgentServiceServer interface {
	mustEmbedUnimplementedAgentServiceServer()
}

func RegisterAgentServiceServer(s grpc.ServiceRegistrar, srv AgentServiceServer) {
	// If the following call panics, it indicates UnimplementedAgentServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AgentService_ServiceDesc, srv)
}

func _AgentService_RegisterAgent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterAgentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).RegisterAgent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentService_RegisterAgent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).RegisterAgent(ctx, req.(*RegisterAgentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_GetAgent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAgentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).GetAgent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentService_GetAgent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).GetAgent(ctx, req.(*GetAgentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_ListAgents_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListAgentsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).ListAgents(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentService_ListAgents_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).ListAgents(ctx, req.(*ListAgentsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_UpdateAgentStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateAgentStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).UpdateAgentStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentService_UpdateAgentStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).UpdateAgentStatus(ctx, req.(*UpdateAgentStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_AgentHeartbeat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AgentHeartbeatRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).AgentHeartbeat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentService_AgentHeartbeat_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).AgentHeartbeat(ctx, req.(*AgentHeartbeatRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AgentService_ServiceDesc is the grpc.ServiceDesc for AgentService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AgentService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "opsmesh.device.v1.AgentService",
	HandlerType: (*AgentServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RegisterAgent",
			Handler:    _AgentService_RegisterAgent_Handler,
		},
		{
			MethodName: "GetAgent",
			Handler:    _AgentService_GetAgent_Handler,
		},
		{
			MethodName: "ListAgents",
			Handler:    _AgentService_ListAgents_Handler,
		},
		{
			MethodName: "UpdateAgentStatus",
			Handler:    _AgentService_UpdateAgentStatus_Handler,
		},
		{
			MethodName: "AgentHeartbeat",
			Handler:    _AgentService_AgentHeartbeat_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "device.proto",
}

const (
	CMDBService_CreateCI_FullMethodName         = "/opsmesh.device.v1.CMDBService/CreateCI"
	CMDBService_GetCI_FullMethodName            = "/opsmesh.device.v1.CMDBService/GetCI"
	CMDBService_UpdateCI_FullMethodName         = "/opsmesh.device.v1.CMDBService/UpdateCI"
	CMDBService_DeleteCI_FullMethodName         = "/opsmesh.device.v1.CMDBService/DeleteCI"
	CMDBService_ListCIs_FullMethodName          = "/opsmesh.device.v1.CMDBService/ListCIs"
	CMDBService_CreateCIRelation_FullMethodName = "/opsmesh.device.v1.CMDBService/CreateCIRelation"
	CMDBService_GetCIRelations_FullMethodName   = "/opsmesh.device.v1.CMDBService/GetCIRelations"
)

// CMDBServiceClient is the client API for CMDBService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// CMDBService provides Configuration Item management and relationships.
type CMDBServiceClient interface {
	// CreateCI creates a new configuration item.
	CreateCI(ctx context.Context, in *CreateCIRequest, opts ...grpc.CallOption) (*CI, error)
	// GetCI retrieves a CI by ID.
	GetCI(ctx context.Context, in *GetCIRequest, opts ...grpc.CallOption) (*CI, error)
	// UpdateCI updates a CI.
	UpdateCI(ctx context.Context, in *UpdateCIRequest, opts ...grpc.CallOption) (*CI, error)
	// DeleteCI removes a CI.
	DeleteCI(ctx context.Context, in *DeleteCIRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// ListCIs lists CIs with optional filtering.
	ListCIs(ctx context.Context, in *ListCIsRequest, opts ...grpc.CallOption) (*ListCIsResponse, error)
	// CreateCIRelation creates a relationship between two CIs.
	CreateCIRelation(ctx context.Context, in *CreateCIRelationRequest, opts ...grpc.CallOption) (*CIRelation, error)
	// GetCIRelations retrieves relations for a CI.
	GetCIRelations(ctx context.Context, in *GetCIRelationsRequest, opts ...grpc.CallOption) (*GetCIRelationsResponse, error)
}

type cMDBServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewCMDBServiceClient(cc grpc.ClientConnInterface) CMDBServiceClient {
	return &cMDBServiceClient{cc}
}

func (c *cMDBServiceClient) CreateCI(ctx context.Context, in *CreateCIRequest, opts ...grpc.CallOption) (*CI, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CI)
	err := c.cc.Invoke(ctx, CMDBService_CreateCI_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cMDBServiceClient) GetCI(ctx context.Context, in *GetCIRequest, opts ...grpc.CallOption) (*CI, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CI)
	err := c.cc.Invoke(ctx, CMDBService_GetCI_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cMDBServiceClient) UpdateCI(ctx context.Context, in *UpdateCIRequest, opts ...grpc.CallOption) (*CI, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CI)
	err := c.cc.Invoke(ctx, CMDBService_UpdateCI_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cMDBServiceClient) DeleteCI(ctx context.Context, in *DeleteCIRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, CMDBService_DeleteCI_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cMDBServiceClient) ListCIs(ctx context.Context, in *ListCIsRequest, opts ...grpc.CallOption) (*ListCIsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListCIsResponse)
	err := c.cc.Invoke(ctx, CMDBService_ListCIs_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cMDBServiceClient) CreateCIRelation(ctx context.Context, in *CreateCIRelationRequest, opts ...grpc.CallOption) (*CIRelation, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CIRelation)
	err := c.cc.Invoke(ctx, CMDBService_CreateCIRelation_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cMDBServiceClient) GetCIRelations(ctx context.Context, in *GetCIRelationsRequest, opts ...grpc.CallOption) (*GetCIRelationsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetCIRelationsResponse)
	err := c.cc.Invoke(ctx, CMDBService_GetCIRelations_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CMDBServiceServer is the server API for CMDBService service.
// All implementations must embed UnimplementedCMDBServiceServer
// for forward compatibility.
//
// CMDBService provides Configuration Item management and relationships.
type CMDBServiceServer interface {
	// CreateCI creates a new configuration item.
	CreateCI(context.Context, *CreateCIRequest) (*CI, error)
	// GetCI retrieves a CI by ID.
	GetCI(context.Context, *GetCIRequest) (*CI, error)
	// UpdateCI updates a CI.
	UpdateCI(context.Context, *UpdateCIRequest) (*CI, error)
	// DeleteCI removes a CI.
	DeleteCI(context.Context, *DeleteCIRequest) (*emptypb.Empty, error)
	// ListCIs lists CIs with optional filtering.
	ListCIs(context.Context, *ListCIsRequest) (*ListCIsResponse, error)
	// CreateCIRelation creates a relationship between two CIs.
	CreateCIRelation(context.Context, *CreateCIRelationRequest) (*CIRelation, error)
	// GetCIRelations retrieves relations for a CI.
	GetCIRelations(context.Context, *GetCIRelationsRequest) (*GetCIRelationsResponse, error)
	mustEmbedUnimplementedCMDBServiceServer()
}

// UnimplementedCMDBServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCMDBServiceServer struct{}

func (UnimplementedCMDBServiceServer) CreateCI(context.Context, *CreateCIRequest) (*CI, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateCI not implemented")
}
func (UnimplementedCMDBServiceServer) GetCI(context.Context, *GetCIRequest) (*CI, error) {
	return nil, status.Error(codes.Unimplemented, "method GetCI not implemented")
}
func (UnimplementedCMDBServiceServer) UpdateCI(context.Context, *UpdateCIRequest) (*CI, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateCI not implemented")
}
func (UnimplementedCMDBServiceServer) DeleteCI(context.Context, *DeleteCIRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteCI not implemented")
}
func (UnimplementedCMDBServiceServer) ListCIs(context.Context, *ListCIsRequest) (*ListCIsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListCIs not implemented")
}
func (UnimplementedCMDBServiceServer) CreateCIRelation(context.Context, *CreateCIRelationRequest) (*CIRelation, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateCIRelation not implemented")
}
func (UnimplementedCMDBServiceServer) GetCIRelations(context.Context, *GetCIRelationsRequest) (*GetCIRelationsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetCIRelations not implemented")
}
func (UnimplementedCMDBServiceServer) mustEmbedUnimplementedCMDBServiceServer() {}
func (UnimplementedCMDBServiceServer) testEmbeddedByValue()                     {}

// UnsafeCMDBServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CMDBServiceServer will
// result in compilation errors.
type UnsafeCMDBServiceServer interface {
	mustEmbedUnimplementedCMDBServiceServer()
}

func RegisterCMDBServiceServer(s grpc.ServiceRegistrar, srv CMDBServiceServer) {
	// If the following call panics, it indicates UnimplementedCMDBServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&CMDBService_ServiceDesc, srv)
}

func _CMDBService_CreateCI_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateCIRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CMDBServiceServer).CreateCI(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CMDBService_CreateCI_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CMDBServiceServer).CreateCI(ctx, req.(*CreateCIRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CMDBService_GetCI_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCIRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CMDBServiceServer).GetCI(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CMDBService_GetCI_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CMDBServiceServer).GetCI(ctx, req.(*GetCIRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CMDBService_UpdateCI_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateCIRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CMDBServiceServer).UpdateCI(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CMDBService_UpdateCI_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CMDBServiceServer).UpdateCI(ctx, req.(*UpdateCIRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CMDBService_DeleteCI_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteCIRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CMDBServiceServer).DeleteCI(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CMDBService_DeleteCI_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CMDBServiceServer).DeleteCI(ctx, req.(*DeleteCIRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CMDBService_ListCIs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListCIsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CMDBServiceServer).ListCIs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CMDBService_ListCIs_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CMDBServiceServer).ListCIs(ctx, req.(*ListCIsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CMDBService_CreateCIRelation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateCIRelationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CMDBServiceServer).CreateCIRelation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CMDBService_CreateCIRelation_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CMDBServiceServer).CreateCIRelation(ctx, req.(*CreateCIRelationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CMDBService_GetCIRelations_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCIRelationsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CMDBServiceServer).GetCIRelations(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CMDBService_GetCIRelations_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CMDBServiceServer).GetCIRelations(ctx, req.(*GetCIRelationsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// CMDBService_ServiceDesc is the grpc.ServiceDesc for CMDBService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CMDBService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "opsmesh.device.v1.CMDBService",
	HandlerType: (*CMDBServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateCI",
			Handler:    _CMDBService_CreateCI_Handler,
		},
		{
			MethodName: "GetCI",
			Handler:    _CMDBService_GetCI_Handler,
		},
		{
			MethodName: "UpdateCI",
			Handler:    _CMDBService_UpdateCI_Handler,
		},
		{
			MethodName: "DeleteCI",
			Handler:    _CMDBService_DeleteCI_Handler,
		},
		{
			MethodName: "ListCIs",
			Handler:    _CMDBService_ListCIs_Handler,
		},
		{
			MethodName: "CreateCIRelation",
			Handler:    _CMDBService_CreateCIRelation_Handler,
		},
		{
			MethodName: "GetCIRelations",
			Handler:    _CMDBService_GetCIRelations_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "device.proto",
}

const (
	DiscoveryService_StartDiscovery_FullMethodName        = "/opsmesh.device.v1.DiscoveryService/StartDiscovery"
	DiscoveryService_GetDiscoveryStatus_FullMethodName    = "/opsmesh.device.v1.DiscoveryService/GetDiscoveryStatus"
	DiscoveryService_ListDiscoveredDevices_FullMethodName = "/opsmesh.device.v1.DiscoveryService/ListDiscoveredDevices"
)

// DiscoveryServiceClient is the client API for DiscoveryService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// DiscoveryService provides network discovery capabilities.
type DiscoveryServiceClient interface {
	// StartDiscovery initiates a network discovery scan.
	StartDiscovery(ctx context.Context, in *StartDiscoveryRequest, opts ...grpc.CallOption) (*DiscoveryJob, error)
	// GetDiscoveryStatus returns the status of a discovery job.
	GetDiscoveryStatus(ctx context.Context, in *GetDiscoveryStatusRequest, opts ...grpc.CallOption) (*DiscoveryJob, error)
	// ListDiscoveredDevices lists devices found during discovery.
	ListDiscoveredDevices(ctx context.Context, in *ListDiscoveredDevicesRequest, opts ...grpc.CallOption) (*ListDiscoveredDevicesResponse, error)
}

type discoveryServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewDiscoveryServiceClient(cc grpc.ClientConnInterface) DiscoveryServiceClient {
	return &discoveryServiceClient{cc}
}

func (c *discoveryServiceClient) StartDiscovery(ctx context.Context, in *StartDiscoveryRequest, opts ...grpc.CallOption) (*DiscoveryJob, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DiscoveryJob)
	err := c.cc.Invoke(ctx, DiscoveryService_StartDiscovery_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *discoveryServiceClient) GetDiscoveryStatus(ctx context.Context, in *GetDiscoveryStatusRequest, opts ...grpc.CallOption) (*DiscoveryJob, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DiscoveryJob)
	err := c.cc.Invoke(ctx, DiscoveryService_GetDiscoveryStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *discoveryServiceClient) ListDiscoveredDevices(ctx context.Context, in *ListDiscoveredDevicesRequest, opts ...grpc.CallOption) (*ListDiscoveredDevicesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListDiscoveredDevicesResponse)
	err := c.cc.Invoke(ctx, DiscoveryService_ListDiscoveredDevices_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DiscoveryServiceServer is the server API for DiscoveryService service.
// All implementations must embed UnimplementedDiscoveryServiceServer
// for forward compatibility.
//
// DiscoveryService provides network discovery capabilities.
type DiscoveryServiceServer interface {
	// StartDiscovery initiates a network discovery scan.
	StartDiscovery(context.Context, *StartDiscoveryRequest) (*DiscoveryJob, error)
	// GetDiscoveryStatus returns the status of a discovery job.
	GetDiscoveryStatus(context.Context, *GetDiscoveryStatusRequest) (*DiscoveryJob, error)
	// ListDiscoveredDevices lists devices found during discovery.
	ListDiscoveredDevices(context.Context, *ListDiscoveredDevicesRequest) (*ListDiscoveredDevicesResponse, error)
	mustEmbedUnimplementedDiscoveryServiceServer()
}

// UnimplementedDiscoveryServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDiscoveryServiceServer struct{}

func (UnimplementedDiscoveryServiceServer) StartDiscovery(context.Context, *StartDiscoveryRequest) (*DiscoveryJob, error) {
	return nil, status.Error(codes.Unimplemented, "method StartDiscovery not implemented")
}
func (UnimplementedDiscoveryServiceServer) GetDiscoveryStatus(context.Context, *GetDiscoveryStatusRequest) (*DiscoveryJob, error) {
	return nil, status.Error(codes.Unimplemented, "method GetDiscoveryStatus not implemented")
}
func (UnimplementedDiscoveryServiceServer) ListDiscoveredDevices(context.Context, *ListDiscoveredDevicesRequest) (*ListDiscoveredDevicesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListDiscoveredDevices not implemented")
}
func (UnimplementedDiscoveryServiceServer) mustEmbedUnimplementedDiscoveryServiceServer() {}
func (UnimplementedDiscoveryServiceServer) testEmbeddedByValue()                          {}

// UnsafeDiscoveryServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DiscoveryServiceServer will
// result in compilation errors.
type UnsafeDiscoveryServiceServer interface {
	mustEmbedUnimplementedDiscoveryServiceServer()
}

func RegisterDiscoveryServiceServer(s grpc.ServiceRegistrar, srv DiscoveryServiceServer) {
	// If the following call panics, it indicates UnimplementedDiscoveryServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&DiscoveryService_ServiceDesc, srv)
}

func _DiscoveryService_StartDiscovery_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StartDiscoveryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DiscoveryServiceServer).StartDiscovery(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DiscoveryService_StartDiscovery_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DiscoveryServiceServer).StartDiscovery(ctx, req.(*StartDiscoveryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DiscoveryService_GetDiscoveryStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDiscoveryStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DiscoveryServiceServer).GetDiscoveryStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DiscoveryService_GetDiscoveryStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DiscoveryServiceServer).GetDiscoveryStatus(ctx, req.(*GetDiscoveryStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DiscoveryService_ListDiscoveredDevices_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListDiscoveredDevicesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DiscoveryServiceServer).ListDiscoveredDevices(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DiscoveryService_ListDiscoveredDevices_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DiscoveryServiceServer).ListDiscoveredDevices(ctx, req.(*ListDiscoveredDevicesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// DiscoveryService_ServiceDesc is the grpc.ServiceDesc for DiscoveryService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DiscoveryService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "opsmesh.device.v1.DiscoveryService",
	HandlerType: (*DiscoveryServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "StartDiscovery",
			Handler:    _DiscoveryService_StartDiscovery_Handler,
		},
		{
			MethodName: "GetDiscoveryStatus",
			Handler:    _DiscoveryService_GetDiscoveryStatus_Handler,
		},
		{
			MethodName: "ListDiscoveredDevices",
			Handler:    _DiscoveryService_ListDiscoveredDevices_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "device.proto",
}
